const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
let current={},clips=[],timeline=[],lastBlob=null;
const STORE='factpulse-v7';
const OLD=['factpulse-v6','factpulse-v5','factpulse-v4','factpulse-web-v3','factpulse-web-v2','factpulse-web'];
const DEFAULT_FACT="The crew that washes the Burj Khalifa's windows finishes the last pane and immediately starts over.";
const DEFAULT_NUMBERS='24,000 glass panels, 800 meters of drop, three months per cycle';
const DEFAULT_QUERY='skyscraper window cleaning building glass workers';
function clean(t){return String(t||'').trim().replace(/\s+/g,' ')}
function esc(t){return String(t).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function toast(t){let e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function setActiveNav(){let p=document.body.dataset.page||'create';$$('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===p))}
function tokens(q){return clean(q).toLowerCase().split(/[^a-z0-9]+/).filter(w=>w.length>2).slice(0,8)}
function titleCase(s){return clean(s).split(' ').map(w=>w?w[0].toUpperCase()+w.slice(1).toLowerCase():'').join(' ')}
function nums(){let v=$('#numbers')?$('#numbers').value:current.numbers;return clean(v).split(',').map(x=>x.trim()).filter(Boolean)}
function titleFrom(f,q){let l=clean(f+' '+q).toLowerCase();if(l.includes('burj')||l.includes('window'))return 'NEVER FULLY CLEAN';if(l.includes('ocean'))return "EARTH'S HIDDEN WORLD";if(l.includes('space')||l.includes('planet'))return 'SPACE IS NOT EMPTY';if(l.includes('animal'))return 'ANIMALS ARE BUILT DIFFERENT';if(l.includes('money'))return 'SMALL MONEY ADDS UP';let t=tokens(q)[0]||'fact';return titleCase(t)+' FACT'}
function relatedFact(q){q=clean(q||DEFAULT_QUERY);let l=q.toLowerCase();let key=titleCase(q.split(' ').slice(0,4).join(' '));if(l.includes('skyscraper')||l.includes('window'))return "Skyscraper window cleaning never really ends because height, wind, dust, and glass keep turning it into a repeated cycle.";if(l.includes('ocean'))return 'The ocean looks calm from above, but deep water hides pressure, darkness, and distances most people never see.';if(l.includes('space')||l.includes('planet'))return 'Space footage looks quiet, but every shot is showing huge distance, speed, and scale at the same time.';if(l.includes('animal'))return 'Animal clips look simple, but the movement usually shows a survival skill most people miss.';if(l.includes('money'))return 'Money clips become interesting when you notice how small repeated choices turn into large results.';if(l.includes('factory')||l.includes('machine'))return 'Machines look smooth on camera because thousands of small parts repeat the same motion perfectly.';return key+' looks simple at first, but the hidden detail is what makes the video worth watching.'}
function proof(q){let l=clean(q).toLowerCase();if(l.includes('skyscraper')||l.includes('window'))return 'height, wind, dust, repeated cycles';if(l.includes('ocean'))return 'deep pressure, darkness, massive distance';if(l.includes('space'))return 'distance, speed, scale';if(l.includes('animal'))return 'movement, survival, hidden skill';if(l.includes('money'))return 'small choices, repetition, long-term cost';if(l.includes('factory')||l.includes('machine'))return 'repeated motion, precision, scale';return 'hidden detail, scale, repeated pattern'}
function shouldAutoFact(){return !current.fact||current.fact===DEFAULT_FACT||current.autoFact===true}
function updateFactForQuery(q){if(shouldAutoFact()){current.fact=relatedFact(q);current.numbers=proof(q);current.autoFact=true;if($('#fact'))$('#fact').value=current.fact;if($('#numbers'))$('#numbers').value=current.numbers}}
function replace1(t,s,r){let i=t.toLowerCase().indexOf(s.toLowerCase());return i<0?t:t.slice(0,i)+r+t.slice(i+s.length)}
function overlay(f,q){let h=esc(f);nums().slice(0,3).forEach((n,i)=>h=replace1(h,esc(n),'<mark class="'+(i==1?'yellow':i==2?'blue':'')+'">'+esc(n)+'</mark>'));tokens(q).slice(0,2).forEach((w,i)=>{if(h.toLowerCase().includes(w))h=replace1(h,w,'<mark class="'+(i?'blue':'')+'">'+esc(w)+'</mark>')});return h}
function voice(f){let ns=nums();return 'Did you know? '+f+' '+(ns.length?'The key details are: '+ns.join(', ')+'.':'The detail is easy to miss.')+' That is why the clip is more interesting than it looks.'}
function cap(t){return t.replace(/([.!?])\s+/g,'$1|').split('|').filter(Boolean).map(s=>{let w=s.split(' ');if(w.length<=7)return s;let a=[];for(let i=0;i<w.length;i+=7)a.push(w.slice(i,i+7).join(' '));return a.join('\n')})}
function readForm(){let q=$('#query')?clean($('#query').value):(current.query||DEFAULT_QUERY);if($('#query'))current.query=q;updateFactForQuery(q);let f=$('#fact')?clean($('#fact').value):(current.fact||relatedFact(q));let n=$('#numbers')?clean($('#numbers').value):(current.numbers||proof(q));let len=$('#length')?Number($('#length').value):Number(current.length||30);len=Math.max(25,len||30);let ti=titleFrom(f,q),vo=voice(f);current={...current,fact:f,numbers:n,query:q,length:len,title:ti,overlay:overlay(f,q),overlayPlain:'DID YOU KNOW?\n'+f+(n?'\nKey facts: '+n:''),voiceover:vo,captions:cap(vo),description:ti+'\n\n'+f+'\n\n'+(n?'Key facts: '+n+'\n\n':'')+'#shorts #didyouknow #facts #interestingfacts'};save();renderAll()}
function loadKey(){for(let k of [STORE,...OLD]){try{let s=localStorage.getItem(k);if(s){let st=JSON.parse(s);if(st.key)return st.key}}catch(e){}}return ''}
function save(){try{localStorage.setItem(STORE,JSON.stringify({current,clips,timeline,key:$('#pixabayKey')?$('#pixabayKey').value:loadKey()}))}catch(e){}}
function load(){let raw=null;for(let k of [STORE,...OLD]){raw=localStorage.getItem(k);if(raw)break}if(raw){try{let st=JSON.parse(raw);current=st.current||{};clips=st.clips||[];timeline=st.timeline||[];if($('#pixabayKey'))$('#pixabayKey').value=st.key||''}catch(e){}}
if(!current.query)current.query=DEFAULT_QUERY;if(!current.fact){current.fact=relatedFact(current.query);current.numbers=proof(current.query);current.autoFact=true}if($('#query'))$('#query').value=current.query;if($('#fact'))$('#fact').value=current.fact;if($('#numbers'))$('#numbers').value=current.numbers;if($('#length'))$('#length').value=String(Math.max(25,Number(current.length||30)));if($('#pixabayKey')&&!$('#pixabayKey').value)$('#pixabayKey').value=loadKey();readForm()}
function renderAll(){renderPreview();renderPost();renderClips();renderTimeline()}
function renderPreview(){let pt=$('#previewText'),tt=$('#previewTitle');if(pt)pt.innerHTML=current.overlay||overlay(current.fact,current.query);if(tt)tt.textContent=current.title||titleFrom(current.fact,current.query);let bg=$('#clipBg'),pv=$('#previewVideo'),first=timeline[0];if(bg&&pv&&first){pv.src=first.videoUrl;bg.classList.add('on');pv.play().catch(()=>{})}else if(bg)bg.classList.remove('on')}
function renderPost(){let box=$('#postBox');if(!box)return;box.textContent=['TITLE: '+(current.title||''),'','VIDEO LENGTH: '+Math.max(25,Number(current.length||30))+' seconds','','VOICEOVER:',current.voiceover||'','','CAPTIONS:',(current.captions||[]).join('\n\n'),'','DESCRIPTION:',current.description||'','','CREDITS:',timeline.map(c=>c.credit+' via '+c.source+': '+c.pageUrl).join('\n')].join('\n')}
function score(c,ts){let text=(c.tags+' '+c.credit+' '+c.pageUrl).toLowerCase();let s=0;ts.forEach(t=>{if(text.includes(t))s+=3});if(c.duration>=25)s+=1;return s}
async function searchClips(many){readForm();let key=clean($('#pixabayKey')?$('#pixabayKey').value:'');if(!key){toast('Paste your Pixabay key first.');return}clips=[];renderClips();$('#clipCount').textContent='Searching for videos related to: '+current.query;try{let pages=many?5:1,per=many?200:40,all=[],ts=tokens(current.query);for(let p=1;p<=pages;p++){let url='https://pixabay.com/api/videos/?key='+encodeURIComponent(key)+'&q='+encodeURIComponent(current.query)+'&orientation=vertical&per_page='+per+'&page='+p+'&safesearch=true&order=popular';let r=await fetch(url);if(!r.ok)throw Error('bad');let j=await r.json();(j.hits||[]).forEach(v=>{let file=v.videos&&((v.videos.medium)||(v.videos.small)||(v.videos.large)||(v.videos.tiny));if(file&&file.url)all.push({id:'pixabay-'+v.id,source:'Pixabay',credit:v.user||'Pixabay creator',pageUrl:v.pageURL,videoUrl:file.url,previewUrl:file.url,duration:v.duration||0,tags:v.tags||current.query,thumb:v.picture_id?'https://i.vimeocdn.com/video/'+v.picture_id+'_640x360.jpg':''})})}all.sort((a,b)=>score(b,ts)-score(a,ts));clips=Array.from(new Map(all.map(c=>[c.id,c])).values()).slice(0,many?1000:80);save();renderClips();$('#clipCount').textContent=clips.length+' videos loaded for: '+current.query;toast(clips.length+' related videos loaded')}catch(e){$('#clipCount').textContent='Search failed';toast('Search failed. Check key or internet.')}}
function addClip(i){let c=clips[i];if(!c)return;timeline.push(c);if(shouldAutoFact()){current.fact=relatedFact(c.tags||current.query);current.numbers=proof(c.tags||current.query);current.autoFact=true;readForm()}save();renderAll();toast('Clip added')}
function renderClips(){let g=$('#clipGrid');if(!g)return;if($('#clipCount'))$('#clipCount').textContent=clips.length?clips.length+' videos loaded for: '+(current.query||'search'):'0 clips loaded';g.innerHTML='';if(!clips.length){g.innerHTML='<div class="box">No videos loaded yet. Tap Find legal clips. Results will match your search phrase.</div>';return}clips.forEach((c,i)=>{let el=document.createElement('article');el.className='clip';el.dataset.i=i;el.innerHTML='<div class="thumb"><video muted playsinline preload="metadata" src="'+c.previewUrl+'"></video></div><strong>'+esc(c.source)+' video '+(i+1)+'</strong><small>Search match: '+esc(current.query)+'</small><small>Tags: '+esc(c.tags||'related video')+'</small><small>'+(c.duration?c.duration+' sec source clip':'Legal stock video')+'</small><div class="row"><button type="button" data-add="'+i+'">Add</button><a href="'+c.pageUrl+'" target="_blank">Source</a></div>';g.appendChild(el)});g.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();addClip(Number(b.dataset.add))}));g.querySelectorAll('.clip').forEach(card=>{let v=card.querySelector('video');card.addEventListener('touchstart',()=>v&&v.play().catch(()=>{}),{passive:true});card.addEventListener('click',e=>{if(e.target.closest('a,button'))return;addClip(Number(card.dataset.i))})})}
function renderTimeline(){let e=$('#timeline');if(!e)return;if($('#timelineCount'))$('#timelineCount').textContent=timeline.length+' clips selected. Final length: '+Math.max(25,Number(current.length||30))+' seconds.';e.innerHTML='';if(!timeline.length){e.innerHTML='<div class="box">No clips added yet. Go to Clips and tap a video card.</div>';return}timeline.forEach((c,i)=>{let it=document.createElement('div');it.className='item';it.innerHTML='<div><strong>Clip '+(i+1)+' - '+c.source+'</strong><small>'+esc(c.tags||current.query)+'</small><small>'+esc(c.pageUrl)+'</small></div><button type="button" data-rm="'+i+'">×</button>';e.appendChild(it)});e.querySelectorAll('[data-rm]').forEach(b=>b.addEventListener('click',()=>{timeline.splice(Number(b.dataset.rm),1);save();renderAll()}))}
function blobFile(name,content,type){let blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function pack(){readForm();return{title:current.title,fact:current.fact,overlay:current.overlayPlain,lengthSeconds:Math.max(25,Number(current.length||30)),searchQuery:current.query,voiceover:current.voiceover,captions:current.captions,description:current.description,selectedClips:timeline.map(c=>({source:c.source,creator:c.credit,pageUrl:c.pageUrl,videoUrl:c.videoUrl,tags:c.tags,duration:c.duration}))}}
function loadVideo(src){return new Promise((res,rej)=>{let v=document.createElement('video');v.crossOrigin='anonymous';v.muted=true;v.playsInline=true;v.src=src;v.preload='auto';v.onloadeddata=()=>res(v);v.onerror=rej})}
function drawCover(ctx,v,x,y,w,h){let vw=v.videoWidth||720,vh=v.videoHeight||1280,sc=Math.max(w/vw,h/vh),sw=w/sc,sh=h/sc,sx=(vw-sw)/2,sy=(vh-sh)/2;ctx.drawImage(v,sx,sy,sw,sh,x,y,w,h)}
function wrap(ctx,t,x,y,w,lh){let words=t.split(' '),line='';ctx.textAlign='center';for(let n=0;n<words.length;n++){let test=line+words[n]+' ';if(ctx.measureText(test).width>w&&n>0){ctx.fillText(line.trim(),x,y);line=words[n]+' ';y+=lh}else line=test}ctx.fillText(line.trim(),x,y)}
function fallback(ctx,top,bottom){let g=ctx.createLinearGradient(0,top,720,1280-bottom);g.addColorStop(0,'#79c5ff');g.addColorStop(.5,'#3189d5');g.addColorStop(1,'#095b9a');ctx.fillStyle=g;ctx.fillRect(0,top,720,1280-top-bottom)}
async function renderVideo(){readForm();let can=$('#canvas'),ctx=can.getContext('2d'),dur=Math.max(25,Number(current.length||30)),fps=24;if(!can.captureStream||!window.MediaRecorder){toast('This browser cannot render video. Use edit pack.');return}let stream=can.captureStream(fps),rec=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm'}),chunks=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};let done=new Promise(r=>rec.onstop=()=>r(new Blob(chunks,{type:'video/webm'})));let vids=[];try{for(let c of timeline)vids.push(await loadVideo(c.videoUrl))}catch(e){toast('Some clips blocked rendering. Rendering fallback.')}rec.start();let start=performance.now();function frame(now){let t=Math.min((now-start)/1000,dur),top=435,bottom=120;ctx.fillStyle='#050505';ctx.fillRect(0,0,720,1280);if(vids.length){let seg=dur/vids.length,i=Math.min(vids.length-1,Math.floor(t/seg)),v=vids[i],lt=(t-i*seg)%Math.max(1,v.duration||4);try{if(Math.abs(v.currentTime-lt)>.15)v.currentTime=lt;drawCover(ctx,v,0,top,720,1280-top-bottom)}catch(e){fallback(ctx,top,bottom)}}else fallback(ctx,top,bottom);ctx.fillStyle='#030303';ctx.fillRect(0,0,720,top);ctx.fillStyle='#18f038';ctx.font='900 64px -apple-system,Segoe UI,sans-serif';ctx.textAlign='center';ctx.fillText('DID YOU KNOW?',360,86);ctx.fillStyle='white';ctx.font='900 39px -apple-system,Segoe UI,sans-serif';wrap(ctx,current.fact,360,140,660,43);ctx.fillStyle='#050505';ctx.fillRect(0,1160,720,120);ctx.fillStyle='white';ctx.font='bold 32px -apple-system,Segoe UI,sans-serif';ctx.textAlign='left';ctx.fillText('@FactPulse',92,1210);ctx.font='bold 26px -apple-system,Segoe UI,sans-serif';ctx.fillText(current.title,28,1256);if($('#progress'))$('#progress').style.width=(t/dur*100)+'%';if(t<dur)requestAnimationFrame(frame);else rec.stop()}requestAnimationFrame(frame);lastBlob=await done;let url=URL.createObjectURL(lastBlob);$('#videoOut').innerHTML='<video controls playsinline src="'+url+'"></video><a class="btn primary" href="'+url+'" download="factpulse-short.webm" style="margin-top:10px">Download 25+ second video</a><button class="btn primary" id="shareVideo" type="button" style="margin-top:10px;width:100%">Share to YouTube</button><a class="btn secondary" href="https://studio.youtube.com" target="_blank" style="margin-top:10px">Open YouTube Studio</a>';$('#shareVideo').addEventListener('click',shareVideo);toast('Video rendered. Length: '+dur+' seconds')}
async function shareVideo(){if(!lastBlob){toast('Render video first.');return}let file=new File([lastBlob],'factpulse-short.webm',{type:'video/webm'});try{if(navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({files:[file],title:current.title,text:current.description});toast('Choose YouTube in the share sheet.')}else toast('Download video, then upload in YouTube Studio.')}catch(e){toast('Share cancelled.')}}
function bind(){setActiveNav();if($('#factForm'))$('#factForm').addEventListener('submit',e=>{e.preventDefault();readForm();location.href='clips-v7.html'});if($('#query'))$('#query').addEventListener('input',()=>{current.query=clean($('#query').value);updateFactForQuery(current.query);readForm()});if($('#searchClips'))$('#searchClips').addEventListener('click',()=>searchClips(false));if($('#searchMany'))$('#searchMany').addEventListener('click',()=>searchClips(true));if($('#renderBtn'))$('#renderBtn').addEventListener('click',renderVideo);if($('#downloadPack'))$('#downloadPack').addEventListener('click',()=>blobFile('factpulse-edit-pack.json',JSON.stringify(pack(),null,2),'application/json'));if($('#copyPost'))$('#copyPost').addEventListener('click',async()=>{readForm();await navigator.clipboard.writeText($('#postBox').textContent);toast('Post copied')});if($('#copyPack'))$('#copyPack').addEventListener('click',async()=>{readForm();await navigator.clipboard.writeText(JSON.stringify(pack(),null,2));toast('Pack copied')});if($('#pixabayKey'))$('#pixabayKey').addEventListener('input',save)}
load();bind();renderAll();