const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
let current={},clips=[],timeline=[],lastBlob=null;
const STORE='factpulse-v12',OLD=['factpulse-v11','factpulse-v10','factpulse-v9'];
function clean(t){return String(t||'').trim().replace(/\s+/g,' ')}
function esc(t){return String(t||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function toast(t){let e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function words(t){return clean(t).toLowerCase().split(/[^a-z0-9]+/).filter(w=>w.length>2&&!['the','and','that','with','from','this','when','what','why','how','are','was','were','you','your','his','her','their','into','about','after','before'].includes(w)).slice(0,18)}
function titleCase(s){return clean(s).split(' ').map(w=>w?w[0].toUpperCase()+w.slice(1).toLowerCase():'').join(' ')}
function isMLK(t){t=clean(t).toLowerCase();return t.includes('martin luther king')||t.includes('mlk')||t.includes('civil rights speech')}
function defaultScene(subject,fact){let t=(subject+' '+fact).toLowerCase();if(isMLK(t))return 'Martin Luther King Jr civil rights march speech crowd';
let map=[['court','courtroom judge lawyer courthouse trial hearing'],['trial','courtroom judge lawyer courthouse trial hearing'],['lawsuit','courtroom lawyer documents courthouse'],['crime','police lights courthouse evidence documents'],['money','money cash bank finance coins wallet'],['space','space rocket planet astronaut galaxy'],['ocean','ocean waves underwater sea marine'],['animal','wild animals wildlife nature close up'],['history','archive footage crowd speech old city street'],['war','military soldiers battlefield archive footage'],['school','students classroom books studying'],['health','hospital doctor patient medical'],['food','food cooking kitchen close up'],['science','science lab microscope experiment'],['technology','computer phone circuit technology'],['weather','storm rain lightning clouds'],['sports','stadium athlete sports training'],['music','microphone concert crowd stage'],['car','cars road traffic city driving'],['earth','nature forest mountains landscape']];
for(let [k,v] of map){if(t.includes(k))return v}return words(subject+' '+fact).slice(0,6).join(' ')}
function titleFrom(subject,fact){let base=clean(subject)||words(fact).slice(0,4).join(' ');if(isMLK(base+' '+fact))return 'THE SPEECH THAT MOVED HISTORY';return (titleCase(base||'Did You Know')+' Fact').toUpperCase().slice(0,70)}
function loadField(name){for(let k of [STORE,...OLD]){try{let s=localStorage.getItem(k);if(s){let st=JSON.parse(s);if(st[name])return st[name];if(name==='pixabayKey'&&st.key)return st.key}}catch(e){}}return ''}
function save(){try{localStorage.setItem(STORE,JSON.stringify({current,clips,timeline,pixabayKey:$('#pixabayKey')?$('#pixabayKey').value:loadField('pixabayKey'),pexelsKey:$('#pexelsKey')?$('#pexelsKey').value:loadField('pexelsKey'),licenseMode:$('#licenseMode')?$('#licenseMode').value:(current.licenseMode||'broad')}))}catch(e){}}
function buildSearches(subject,fact,scene){let exact=clean(subject);let visual=clean(scene)||defaultScene(subject,fact);let factKeys=words(fact).slice(0,6).join(' ');let out=[];if(exact)out.push(exact);if(isMLK(subject+' '+fact)){out.push('Martin Luther King Jr');out.push('civil rights march speech crowd');out.push('civil rights protest crowd podium microphone');out.push('1960s civil rights march archive footage')}
out.push(visual);out.push(exact+' '+visual);out.push(factKeys);out.push(visual+' b roll');return Array.from(new Set(out.map(clean).filter(Boolean))).slice(0,8)}
function makeCaption(subject,fact){let s=clean(subject),f=clean(fact);if(isMLK(s+' '+f))return 'Martin Luther King Jr. became one of the most important voices in American history because his speeches helped push civil rights into the national spotlight.';
if(f)return f.length>260?f.slice(0,257)+'...':f;return 'This fact becomes easier to understand when the clip shows the setting, movement, scale, and context.'}
function rebuild(){let subject=$('#subject')?clean($('#subject').value):(current.subject||'');let fact=$('#fact')?clean($('#fact').value):(current.fact||'');let scene=$('#scene')?clean($('#scene').value):(current.scene||defaultScene(subject,fact));let details=$('#numbers')?clean($('#numbers').value):(current.numbers||words(fact).slice(0,4).join(', '));let len=$('#length')?Number($('#length').value):Number(current.length||30);len=Math.min(45,Math.max(25,len||30));let searchList=buildSearches(subject,fact,scene);let caption=makeCaption(subject,fact);let voice='Did you know? '+caption+' The key details are: '+(details||words(caption).slice(0,4).join(', '))+'.';current={...current,subject,fact:caption,rawFact:fact,scene,numbers:details,length:len,searchList,query:searchList[0],title:titleFrom(subject,caption),voiceover:voice,captions:voice.replace(/([.!?])\s+/g,'$1|').split('|').filter(Boolean),description:titleFrom(subject,caption)+'\n\n'+caption+'\n\nKey details: '+details+'\n\n#shorts #facts #didyouknow #history #interestingfacts',licenseMode:$('#licenseMode')?$('#licenseMode').value:(current.licenseMode||'broad')};save();renderSearchPlan();renderPost();renderTimeline();renderClips()}
function load(){let raw=null;for(let k of [STORE,...OLD]){raw=localStorage.getItem(k);if(raw)break}if(raw){try{let st=JSON.parse(raw);current=st.current||{};clips=st.clips||[];timeline=st.timeline||[];if($('#pixabayKey'))$('#pixabayKey').value=st.pixabayKey||st.key||'';if($('#pexelsKey'))$('#pexelsKey').value=st.pexelsKey||'';if($('#licenseMode'))$('#licenseMode').value=st.licenseMode||current.licenseMode||'broad'}catch(e){}}
if(!current.subject)current.subject='Martin Luther King Jr';if(!current.rawFact&&!current.fact)current.rawFact='He used speeches, marches, and public pressure to push civil rights into the center of American history.';if(!current.scene)current.scene=defaultScene(current.subject,current.rawFact||current.fact);if($('#subject'))$('#subject').value=current.subject||'';if($('#fact'))$('#fact').value=current.rawFact||current.fact||'';if($('#scene'))$('#scene').value=current.scene||'';if($('#numbers'))$('#numbers').value=current.numbers||'';if($('#length'))$('#length').value=String(Math.min(45,Math.max(25,Number(current.length||30))));if($('#pixabayKey')&&!$('#pixabayKey').value)$('#pixabayKey').value=loadField('pixabayKey');if($('#pexelsKey')&&!$('#pexelsKey').value)$('#pexelsKey').value=loadField('pexelsKey');rebuild()}
function renderSearchPlan(){let e=$('#searchPlan');if(!e)return;e.textContent=(current.searchList||[]).map((x,i)=>(i+1)+'. '+x).join('\n')}
function isPublicLicense(x){x=clean(x).toLowerCase();return x.includes('public domain')||x.includes('cc0')||x.includes('pdm')}
function isPermissiveLicense(x){x=clean(x).toLowerCase();return isPublicLicense(x)||x.includes('cc by')||x.includes('creative commons attribution')||x.includes('cc-by')||x.includes('pixabay')||x.includes('pexels')||x===''||x.includes('verify')}
function matchScore(c,ts,subjectTokens){let text=(c.tags+' '+c.source+' '+c.license+' '+c.pageUrl+' '+c.credit).toLowerCase();let s=0;ts.forEach(t=>{if(text.includes(t))s+=2});subjectTokens.forEach(t=>{if(text.includes(t))s+=8});if(c.match==='exact')s+=20;if(c.match==='related')s+=5;if(isPublicLicense(c.license))s+=4;if(c.source==='Wikimedia Commons')s+=3;if(c.source==='Internet Archive')s+=2;if(c.duration>=25)s+=1;return s}
async function searchCommons(q,many,mode,match){let limit=many?500:80,all=[],offset=0;while(all.length<limit){let url='https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrnamespace=6&gsrlimit=50&gsroffset='+offset+'&gsrsearch='+encodeURIComponent(q+' filetype:video')+'&prop=imageinfo&iiprop=url|mime|extmetadata&format=json&origin=*';let r=await fetch(url);if(!r.ok)break;let j=await r.json();let pages=j.query&&j.query.pages?Object.values(j.query.pages):[];pages.forEach(p=>{let ii=p.imageinfo&&p.imageinfo[0];if(!ii||!ii.url||!(ii.mime||'').startsWith('video/'))return;let meta=ii.extmetadata||{};let lic=(meta.LicenseShortName&&meta.LicenseShortName.value)||(meta.UsageTerms&&meta.UsageTerms.value)||'Unknown license';let ok=mode==='public'?isPublicLicense(lic):isPermissiveLicense(lic);if(!ok)return;let name=(p.title||'File').replace(/^File:/,'');all.push({id:'commons-'+p.pageid,source:'Wikimedia Commons',credit:(meta.Artist&&meta.Artist.value?meta.Artist.value.replace(/<[^>]+>/g,''):'Wikimedia contributor'),pageUrl:'https://commons.wikimedia.org/wiki/'+encodeURIComponent(p.title.replaceAll(' ','_')),videoUrl:ii.url,previewUrl:ii.url,duration:0,tags:name+' '+q,license:lic,match})});if(!j.continue||!j.continue.gsroffset)break;offset=j.continue.gsroffset}return all}
async function searchArchive(q,many,mode,match){let rows=many?1000:100;let url='https://archive.org/advancedsearch.php?q='+encodeURIComponent(q+' AND mediatype:movies')+'&fl[]=identifier&fl[]=title&fl[]=description&fl[]=licenseurl&fl[]=rights&rows='+rows+'&page=1&output=json';let r=await fetch(url);if(!r.ok)return[];let j=await r.json(),docs=(j.response&&j.response.docs)||[],out=[];let usable=docs.filter(d=>{let lic=(d.licenseurl||'')+' '+(d.rights||'');return mode==='public'?isPublicLicense(lic):isPermissiveLicense(lic)}).slice(0,many?150:50);for(let d of usable){try{let m=await fetch('https://archive.org/metadata/'+encodeURIComponent(d.identifier));if(!m.ok)continue;let meta=await m.json();let file=(meta.files||[]).find(f=>/\.mp4$/i.test(f.name)&&!String(f.name).toLowerCase().includes('thumb'));if(!file)continue;let lic=(d.licenseurl||d.rights||'verify source rights');if(mode==='public'&&!isPublicLicense(lic))continue;let src='https://archive.org/download/'+d.identifier+'/'+encodeURIComponent(file.name);out.push({id:'archive-'+d.identifier+'-'+file.name,source:'Internet Archive',credit:d.title||d.identifier,pageUrl:'https://archive.org/details/'+d.identifier,videoUrl:src,previewUrl:src,duration:Math.round(Number(file.length||0))||0,tags:(d.title||q)+' '+(d.description||''),license:lic,match})}catch(e){}}return out}
async function searchPixabay(q,key,many,mode,match){if(!key||mode==='public')return[];let pages=many?5:1,per=many?200:40,all=[];for(let p=1;p<=pages;p++){let url='https://pixabay.com/api/videos/?key='+encodeURIComponent(key)+'&q='+encodeURIComponent(q)+'&orientation=vertical&per_page='+per+'&page='+p+'&safesearch=true&order=popular';let r=await fetch(url);if(!r.ok)break;let j=await r.json();(j.hits||[]).forEach(v=>{let file=v.videos&&((v.videos.medium)||(v.videos.small)||(v.videos.large)||(v.videos.tiny));if(file&&file.url)all.push({id:'pixabay-'+v.id,source:'Pixabay',credit:v.user||'Pixabay creator',pageUrl:v.pageURL,videoUrl:file.url,previewUrl:file.url,duration:v.duration||0,tags:v.tags||q,license:'Pixabay Content License',match})})}return all}
async function searchPexels(q,key,many,mode,match){if(!key||mode==='public')return[];let pages=many?13:1,per=many?80:40,all=[];for(let p=1;p<=pages;p++){let url='https://api.pexels.com/videos/search?query='+encodeURIComponent(q)+'&orientation=portrait&size=medium&per_page='+per+'&page='+p;let r=await fetch(url,{headers:{Authorization:key}});if(!r.ok)break;let j=await r.json();(j.videos||[]).forEach(v=>{let file=(v.video_files||[]).filter(f=>f.link&&f.height>=f.width).sort((a,b)=>Math.abs(a.height-1280)-Math.abs(b.height-1280))[0]||(v.video_files||[])[0];if(file&&file.link)all.push({id:'pexels-'+v.id,source:'Pexels',credit:v.user&&v.user.name||'Pexels creator',pageUrl:v.url,videoUrl:file.link,previewUrl:file.link,duration:v.duration||0,tags:q+' '+(v.user&&v.user.name||''),license:'Pexels License',match})})}return all}
async function searchClips(many){rebuild();let mode=current.licenseMode||'broad';let pix=clean($('#pixabayKey')?$('#pixabayKey').value:''),pex=clean($('#pexelsKey')?$('#pexelsKey').value:'');clips=[];renderClips();$('#clipCount').textContent='Searching exact topic first...';try{let subjectQ=clean(current.subject),queries=current.searchList||[],jobs=[];let exactQueries=subjectQ?[subjectQ,subjectQ+' '+(words(current.rawFact||current.fact).slice(0,3).join(' '))]:[];exactQueries.forEach(q=>jobs.push(searchCommons(q,many,mode,'exact'),searchArchive(q,many,mode,'exact')));queries.forEach((q,i)=>{let match=i<2?'exact':'related';jobs.push(searchCommons(q,many,mode,match),searchArchive(q,many,mode,match),searchPixabay(q,pix,many,mode,match),searchPexels(q,pex,many,mode,match))});let settled=await Promise.allSettled(jobs),results=[];settled.forEach(x=>{if(x.status==='fulfilled')results.push(...x.value)});let ts=words((queries.join(' ')+' '+current.fact)),sub=words(subjectQ);results.sort((a,b)=>matchScore(b,ts,sub)-matchScore(a,ts,sub));clips=Array.from(new Map(results.map(c=>[c.id,c])).values()).slice(0,many?2000:120);save();renderClips();$('#clipCount').textContent=clips.length+' clips loaded for this fact';if(!clips.length)toast('No clips found. Use scene words like speech crowd podium, courtroom, documents, city, lab.');else toast(clips.length+' clips found')}catch(e){$('#clipCount').textContent='Search failed';toast('Search failed. Try simpler scene words.')}}
function addClip(i){let c=clips[i];if(!c)return;timeline.push(c);save();renderTimeline();renderPost();toast('Clip added')}
function modal(){if($('#clipModal'))return;let d=document.createElement('div');d.id='clipModal';d.innerHTML='<div class="modal-card"><button class="modal-close" id="closeModal" type="button">×</button><video id="modalVideo" controls playsinline></video><div class="box" id="modalInfo"></div><div class="two"><button class="btn primary" id="modalAdd" type="button">Add clip</button><a class="btn secondary" id="modalSource" target="_blank">Source</a></div></div>';document.body.appendChild(d);$('#closeModal').onclick=closePreview;d.onclick=e=>{if(e.target.id==='clipModal')closePreview()}}
function openPreview(i){let c=clips[i];if(!c)return;modal();let v=$('#modalVideo');v.src=c.videoUrl;v.play().catch(()=>{});$('#modalInfo').textContent=(c.match==='exact'?'Exact topic match':'Related B-roll')+'\n'+c.source+'\nLicense: '+(c.license||'verify source')+'\nTopic: '+(c.tags||current.query)+'\nLength: '+(c.duration?c.duration+' sec':'unknown');$('#modalSource').href=c.pageUrl;$('#modalAdd').onclick=()=>{addClip(i);closePreview()};$('#clipModal').classList.add('show')}
function closePreview(){let m=$('#clipModal'),v=$('#modalVideo');if(v){v.pause();v.removeAttribute('src')}if(m)m.classList.remove('show')}
function renderClips(){let g=$('#clipGrid');if(!g)return;if($('#clipCount'))$('#clipCount').textContent=clips.length?clips.length+' clips loaded':'0 clips loaded';g.innerHTML='';if(!clips.length){g.innerHTML='<div class="box">No clips loaded yet. Tap Find clips. For people or hard facts, add visual scene words like speech crowd podium, courtroom judge, documents, city street, protest, map, or archive footage.</div>';return}clips.forEach((c,i)=>{let label=c.match==='exact'?'EXACT TOPIC':'RELATED B-ROLL';let el=document.createElement('article');el.className='clip';el.dataset.i=i;el.innerHTML='<div class="thumb"><video muted playsinline preload="metadata" src="'+c.previewUrl+'"></video></div><strong>'+label+' · '+esc(c.source)+'</strong><small>License: '+esc(c.license||'verify source')+'</small><small>Topic: '+esc((c.tags||'related').slice(0,100))+'</small><div class="row"><button type="button" data-preview="'+i+'">Preview</button><button type="button" data-add="'+i+'">Add</button></div><a href="'+c.pageUrl+'" target="_blank">Source</a>';g.appendChild(el)});g.querySelectorAll('[data-add]').forEach(b=>b.onclick=e=>{e.stopPropagation();addClip(Number(b.dataset.add))});g.querySelectorAll('[data-preview]').forEach(b=>b.onclick=e=>{e.stopPropagation();openPreview(Number(b.dataset.preview))});g.querySelectorAll('.clip').forEach(card=>{let v=card.querySelector('video');card.addEventListener('touchstart',()=>v&&v.play().catch(()=>{}),{passive:true});card.onclick=e=>{if(e.target.closest('a,button'))return;openPreview(Number(card.dataset.i))}})}
function renderTimeline(){let e=$('#timeline');if(!e)return;if($('#timelineCount'))$('#timelineCount').textContent=timeline.length+' clips selected. Final length: '+current.length+' seconds.';e.innerHTML='';if(!timeline.length){e.innerHTML='<div class="box">No clips added yet.</div>';return}timeline.forEach((c,i)=>{let it=document.createElement('div');it.className='item';it.innerHTML='<div><strong>Clip '+(i+1)+' · '+(c.match==='exact'?'Exact':'B-roll')+' · '+esc(c.source)+'</strong><small>'+esc(c.license||'verify source')+'</small><small>'+esc(c.pageUrl)+'</small></div><button type="button" data-rm="'+i+'">×</button>';e.appendChild(it)});e.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{timeline.splice(Number(b.dataset.rm),1);save();renderTimeline();renderPost()})}
function renderPost(){let box=$('#postBox');if(!box)return;box.textContent=['TITLE: '+current.title,'','VIDEO LENGTH: '+current.length+' seconds','','VOICEOVER:',current.voiceover,'','CAPTIONS:',(current.captions||[]).join('\n\n'),'','DESCRIPTION:',current.description,'','CREDITS:',timeline.map(c=>c.credit+' via '+c.source+' | '+c.license+' | '+c.pageUrl).join('\n')].join('\n')}
function blobFile(name,content,type){let blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function pack(){rebuild();return{title:current.title,fact:current.fact,subject:current.subject,searchIdeas:current.searchList,lengthSeconds:current.length,voiceover:current.voiceover,captions:current.captions,description:current.description,selectedClips:timeline}}
function loadVideo(src){return new Promise((res,rej)=>{let v=document.createElement('video');v.crossOrigin='anonymous';v.muted=true;v.playsInline=true;v.src=src;v.preload='auto';v.onloadeddata=()=>res(v);v.onerror=rej})}
function drawCover(ctx,v,x,y,w,h){let vw=v.videoWidth||720,vh=v.videoHeight||1280,sc=Math.max(w/vw,h/vh),sw=w/sc,sh=h/sc,sx=(vw-sw)/2,sy=(vh-sh)/2;ctx.drawImage(v,sx,sy,sw,sh,x,y,w,h)}
function wrap(ctx,t,x,y,w,lh,maxLines){let words=t.split(' '),line='',lines=[];for(let n=0;n<words.length;n++){let test=line+words[n]+' ';if(ctx.measureText(test).width>w&&n>0){lines.push(line.trim());line=words[n]+' '}else line=test}lines.push(line.trim());lines.slice(0,maxLines||7).forEach((ln,i)=>ctx.fillText(ln,x,y+i*lh))}
function fallback(ctx,top,bottom){let g=ctx.createLinearGradient(0,top,720,1280-bottom);g.addColorStop(0,'#79c5ff');g.addColorStop(.6,'#246dba');g.addColorStop(1,'#061d36');ctx.fillStyle=g;ctx.fillRect(0,top,720,1280-top-bottom)}
async function renderVideo(){rebuild();let can=$('#canvas'),ctx=can.getContext('2d'),dur=Math.min(45,Math.max(25,Number(current.length||30))),fps=24;if(!can.captureStream||!window.MediaRecorder){toast('This browser cannot render video. Use edit pack.');return}let stream=can.captureStream(fps),rec=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm'}),chunks=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};let done=new Promise(r=>rec.onstop=()=>r(new Blob(chunks,{type:'video/webm'})));let vids=[];try{for(let c of timeline)vids.push(await loadVideo(c.videoUrl))}catch(e){toast('Some clips blocked browser rendering. Rendering fallback.')}rec.start();let start=performance.now();function frame(now){let t=Math.min((now-start)/1000,dur),top=430,bottom=110;ctx.fillStyle='#050505';ctx.fillRect(0,0,720,1280);if(vids.length){let seg=dur/vids.length,i=Math.min(vids.length-1,Math.floor(t/seg)),v=vids[i],lt=(t-i*seg)%Math.max(1,v.duration||4);try{if(Math.abs(v.currentTime-lt)>.15)v.currentTime=lt;drawCover(ctx,v,0,top,720,1280-top-bottom)}catch(e){fallback(ctx,top,bottom)}}else fallback(ctx,top,bottom);ctx.fillStyle='#030303';ctx.fillRect(0,0,720,top);ctx.fillStyle='#18f038';ctx.font='900 56px -apple-system,Segoe UI,sans-serif';ctx.textAlign='center';ctx.fillText('DID YOU KNOW?',360,82);ctx.fillStyle='white';ctx.font='900 35px -apple-system,Segoe UI,sans-serif';wrap(ctx,current.fact,360,137,660,39,7);ctx.fillStyle='#050505';ctx.fillRect(0,1170,720,110);ctx.fillStyle='white';ctx.font='bold 29px -apple-system,Segoe UI,sans-serif';ctx.textAlign='left';ctx.fillText('@FactPulse',28,1215);ctx.font='bold 25px -apple-system,Segoe UI,sans-serif';ctx.fillText(current.title.slice(0,36),28,1256);if($('#progress'))$('#progress').style.width=(t/dur*100)+'%';if(t<dur)requestAnimationFrame(frame);else rec.stop()}requestAnimationFrame(frame);lastBlob=await done;let url=URL.createObjectURL(lastBlob);$('#videoOut').innerHTML='<video controls playsinline src="'+url+'"></video><a class="btn primary" href="'+url+'" download="factpulse-short.webm" style="margin-top:10px">Download styled video</a><button class="btn primary" id="shareVideo" type="button" style="margin-top:10px;width:100%">Share to YouTube</button>';$('#shareVideo').onclick=shareVideo;toast('Styled video rendered. Length: '+dur+' seconds')}
async function shareVideo(){if(!lastBlob){toast('Render video first.');return}let file=new File([lastBlob],'factpulse-short.webm',{type:'video/webm'});try{if(navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({files:[file],title:current.title,text:current.description})}else toast('Download video, then upload in YouTube Studio.')}catch(e){toast('Share cancelled.')}}
function injectStyle(){if($('#modalStyle'))return;let s=document.createElement('style');s.id='modalStyle';s.textContent='#clipModal{position:fixed;inset:0;z-index:200;background:rgba(0,0,0,.86);display:none;align-items:center;justify-content:center;padding:14px}#clipModal.show{display:flex}.modal-card{width:min(96vw,430px);max-height:92vh;overflow:auto;background:#111318;border:1px solid #2a2e38;border-radius:24px;padding:12px}.modal-card video{width:100%;max-height:58vh;background:#000;border-radius:18px}.modal-close{float:right;border:0;border-radius:999px;background:#18f038;color:#051007;font-weight:1000;width:40px;height:40px}.clip{cursor:pointer}.clip>a{display:block;margin-top:0}';document.head.appendChild(s)}
function bind(){injectStyle();$$('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===(document.body.dataset.page||'create')));if($('#factForm'))$('#factForm').onsubmit=e=>{e.preventDefault();rebuild();location.href='clips-v12.html'};if($('#searchClips'))$('#searchClips').onclick=()=>searchClips(false);if($('#searchMany'))$('#searchMany').onclick=()=>searchClips(true);if($('#renderBtn'))$('#renderBtn').onclick=renderVideo;if($('#downloadPack'))$('#downloadPack').onclick=()=>blobFile('factpulse-edit-pack.json',JSON.stringify(pack(),null,2),'application/json');if($('#copyPost'))$('#copyPost').onclick=async()=>{rebuild();await navigator.clipboard.writeText($('#postBox').textContent);toast('Post copied')};['subject','fact','scene','numbers','length','licenseMode','pixabayKey','pexelsKey'].forEach(id=>{let e=$('#'+id);if(e)e.addEventListener('input',rebuild);if(e&&id==='licenseMode')e.addEventListener('change',rebuild)})}
load();bind();renderSearchPlan();renderClips();renderTimeline();renderPost();