const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
let current={},clips=[],timeline=[],lastBlob=null;
const STORE='factpulse-v5';
const OLD_STORES=['factpulse-v4','factpulse-web-v3','factpulse-web-v2','factpulse-web'];
function clean(t){return String(t||'').trim().replace(/\s+/g,' ')}
function esc(t){return String(t).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function toast(t){let e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),1800)}
function pageName(){return document.body.dataset.page||'create'}
function setActiveNav(){let page=pageName();$$('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===page))}
function nums(){let el=$('#numbers');return clean(el?el.value:(current.numbers||'')).split(',').map(x=>x.trim()).filter(Boolean)}
function titleFrom(f){let l=clean(f).toLowerCase();if(l.includes('burj')||l.includes('window'))return 'NEVER FULLY CLEAN';if(l.includes('ocean'))return "EARTH'S HIDDEN WORLD";if(l.includes('venus'))return 'A DAY LONGER THAN A YEAR';if(l.includes('subscription'))return 'SMALL PAYMENTS ADD UP';return 'DID YOU KNOW?'}
function replace1(t,s,r){let i=t.toLowerCase().indexOf(s.toLowerCase());return i<0?t:t.slice(0,i)+r+t.slice(i+s.length)}
function overlayText(f){let h=esc(f);nums().slice(0,3).forEach((n,i)=>{h=replace1(h,esc(n),'<mark class="'+(i==1?'yellow':i==2?'blue':'')+'">'+esc(n)+'</mark>')});let p=h.match(/\b[A-Z][a-z]+(?:\s[A-Z][a-z]+)*\b/);if(p)h=replace1(h,p[0],'<mark>'+p[0]+'</mark>');return h}
function voice(f){let ns=nums();return 'Did you know? '+f+' '+(ns.length?'The numbers make it crazier: '+ns.join(', ')+'.':'The scale is the part people miss.')+' The strange part is not only the size. It is the cycle.'}
function cap(t){return t.replace(/([.!?])\s+/g,'$1|').split('|').filter(Boolean).map(s=>{let w=s.split(' ');if(w.length<=7)return s;let a=[];for(let i=0;i<w.length;i+=7)a.push(w.slice(i,i+7).join(' '));return a.join('\n')})}
function stateFromForm(){let fact=$('#fact')?clean($('#fact').value):current.fact||"The crew that washes the Burj Khalifa's windows finishes the last pane and immediately starts over.";let numbers=$('#numbers')?clean($('#numbers').value):current.numbers||'24,000 glass panels, 800 meters of drop, three months per cycle';let query=$('#query')?clean($('#query').value):current.query||'skyscraper window cleaning building glass workers';let length=$('#length')?Number($('#length').value):Number(current.length||30);let title=titleFrom(fact);let vo=voice(fact);current={fact,numbers,query,length,title,overlay:overlayText(fact),overlayPlain:'DID YOU KNOW?\n'+fact+(numbers?'\nKey facts: '+numbers:''),voiceover:vo,captions:cap(vo),description:title+'\n\n'+fact+'\n\n'+(numbers?'Key facts: '+numbers+'\n\n':'')+'#shorts #didyouknow #facts #interestingfacts'};current.full=['TITLE\n'+title,'TEXT OVERLAY\n'+current.overlayPlain,'VOICEOVER\n'+vo,'CAPTIONS\n'+current.captions.join('\n\n'),'DESCRIPTION\n'+current.description,'CLIPS\n'+timeline.map(c=>c.credit+' via '+c.source+': '+c.pageUrl).join('\n')].join('\n\n');saveState();renderPreview();renderPost();}
function saveState(){try{let key=$('#pixabayKey')?$('#pixabayKey').value:loadKey();localStorage.setItem(STORE,JSON.stringify({current,clips,timeline,key}))}catch(e){}}
function loadKey(){for(let name of [STORE,...OLD_STORES]){try{let s=localStorage.getItem(name);if(s){let st=JSON.parse(s);if(st.key)return st.key}}catch(e){}}return ''}
function loadState(){let raw=null;for(let name of [STORE,...OLD_STORES]){raw=localStorage.getItem(name);if(raw)break}if(raw){try{let st=JSON.parse(raw);current=st.current||{};clips=st.clips||[];timeline=st.timeline||[];if($('#pixabayKey'))$('#pixabayKey').value=st.key||''}catch(e){}}
if(!current.fact){current={fact:"The crew that washes the Burj Khalifa's windows finishes the last pane and immediately starts over.",numbers:'24,000 glass panels, 800 meters of drop, three months per cycle',query:'skyscraper window cleaning building glass workers',length:30};stateFromForm()}else{if($('#fact'))$('#fact').value=current.fact||'';if($('#numbers'))$('#numbers').value=current.numbers||'';if($('#query'))$('#query').value=current.query||'';if($('#length'))$('#length').value=String(current.length||30);if($('#pixabayKey')&&!$('#pixabayKey').value)$('#pixabayKey').value=loadKey();renderPreview();renderPost();renderClips();renderTimeline();}}
function renderPreview(){let pt=$('#previewText'),tt=$('#previewTitle');if(pt)pt.innerHTML=current.overlay||overlayText(current.fact||'');if(tt)tt.textContent=current.title||titleFrom(current.fact||'');let first=timeline[0];let bg=$('#clipBg'),pv=$('#previewVideo');if(bg&&pv&&first){pv.src=first.videoUrl;bg.classList.add('on');pv.play().catch(()=>{})}else if(bg){bg.classList.remove('on')}}
function renderPost(){let box=$('#postBox');if(!box)return;box.textContent=['TITLE: '+(current.title||''),'','VOICEOVER:',current.voiceover||'','','CAPTIONS:',(current.captions||[]).join('\n\n'),'','DESCRIPTION:',current.description||'','','CREDITS:',timeline.map(c=>c.credit+' via '+c.source+': '+c.pageUrl).join('\n')].join('\n')}
async function searchClips(many){stateFromForm();let key=clean($('#pixabayKey')?$('#pixabayKey').value:'');if(!key){toast('Paste your Pixabay key first.');return}clips=[];renderClips();$('#clipCount').textContent='Searching...';try{let pages=many?5:1,per=many?200:40,all=[];for(let p=1;p<=pages;p++){let url='https://pixabay.com/api/videos/?key='+encodeURIComponent(key)+'&q='+encodeURIComponent(current.query)+'&orientation=vertical&per_page='+per+'&page='+p+'&safesearch=true';let r=await fetch(url);if(!r.ok)throw new Error('search failed');let j=await r.json();(j.hits||[]).forEach(v=>{let file=v.videos&&((v.videos.medium)||(v.videos.small)||(v.videos.large)||(v.videos.tiny));if(file&&file.url)all.push({id:'pixabay-'+v.id,source:'Pixabay',credit:v.user||'Pixabay creator',pageUrl:v.pageURL,videoUrl:file.url,previewUrl:file.url,duration:v.duration||0,thumb:v.picture_id?'https://i.vimeocdn.com/video/'+v.picture_id+'_640x360.jpg':''})})}clips=Array.from(new Map(all.map(c=>[c.id,c])).values()).slice(0,many?1000:80);saveState();renderClips();$('#clipCount').textContent=clips.length+' legal clips loaded';toast(clips.length+' legal clips loaded')}catch(e){$('#clipCount').textContent='Search failed';toast('Search failed. Check key or internet.')}}
function addClip(i){let c=clips[i];if(!c)return;timeline.push(c);saveState();renderTimeline();renderPreview();renderPost();toast('Clip added to timeline')}
function renderClips(){let g=$('#clipGrid');if(!g)return;g.innerHTML='';if($('#clipCount'))$('#clipCount').textContent=clips.length+' clips loaded';if(!clips.length){g.innerHTML='<div class="box">No clips loaded yet. Tap Find legal clips.</div>';return}clips.forEach((c,i)=>{let el=document.createElement('article');el.className='clip';el.dataset.i=i;el.innerHTML='<div class="thumb">'+(c.thumb?'<img src="'+c.thumb+'" alt="clip thumbnail">':'<span>CLIP '+(i+1)+'</span>')+'</div><strong>'+c.source+' video '+(i+1)+'</strong><small>Creator: '+c.credit+'</small><small>'+(c.duration?c.duration+' sec':'Legal stock clip')+'</small><div class="row"><button type="button" data-add="'+i+'">Add</button><a href="'+c.pageUrl+'" target="_blank">Source</a></div>';g.appendChild(el)});g.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();addClip(Number(b.dataset.add))}));g.querySelectorAll('.clip').forEach(card=>card.addEventListener('click',e=>{if(e.target.closest('a,button'))return;addClip(Number(card.dataset.i))}))}
function renderTimeline(){let e=$('#timeline');if(!e)return;if($('#timelineCount'))$('#timelineCount').textContent=timeline.length+' clips selected.';e.innerHTML='';if(!timeline.length){e.innerHTML='<div class="box">No clips added yet. Go to Clips and tap a card.</div>';return}timeline.forEach((c,i)=>{let it=document.createElement('div');it.className='item';it.innerHTML='<div><strong>Clip '+(i+1)+' - '+c.source+'</strong><small>'+c.credit+'</small><small>'+c.pageUrl+'</small></div><button type="button" data-rm="'+i+'">×</button>';e.appendChild(it)});e.querySelectorAll('[data-rm]').forEach(b=>b.addEventListener('click',()=>{timeline.splice(Number(b.dataset.rm),1);saveState();renderTimeline();renderPreview();renderPost()}))}
function blobFile(name,content,type){let blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function pack(){stateFromForm();return{title:current.title,fact:current.fact,overlay:current.overlayPlain,voiceover:current.voiceover,captions:current.captions,description:current.description,selectedClips:timeline.map(c=>({source:c.source,creator:c.credit,pageUrl:c.pageUrl,videoUrl:c.videoUrl}))}}
function loadVideo(src){return new Promise((res,rej)=>{let v=document.createElement('video');v.crossOrigin='anonymous';v.muted=true;v.playsInline=true;v.src=src;v.preload='auto';v.onloadeddata=()=>res(v);v.onerror=rej})}
function drawCover(ctx,v,x,y,w,h){let vw=v.videoWidth||720,vh=v.videoHeight||1280,sc=Math.max(w/vw,h/vh),sw=w/sc,sh=h/sc,sx=(vw-sw)/2,sy=(vh-sh)/2;ctx.drawImage(v,sx,sy,sw,sh,x,y,w,h)}
function wrap(ctx,t,x,y,w,lh){let words=t.split(' '),line='';ctx.textAlign='center';for(let n=0;n<words.length;n++){let test=line+words[n]+' ';if(ctx.measureText(test).width>w&&n>0){ctx.fillText(line.trim(),x,y);line=words[n]+' ';y+=lh}else line=test}ctx.fillText(line.trim(),x,y)}
function fallback(ctx,top,bottom){let g=ctx.createLinearGradient(0,top,720,1280-bottom);g.addColorStop(0,'#79c5ff');g.addColorStop(.5,'#3189d5');g.addColorStop(1,'#095b9a');ctx.fillStyle=g;ctx.fillRect(0,top,720,1280-top-bottom)}
async function renderVideo(){stateFromForm();let can=$('#canvas'),ctx=can.getContext('2d'),dur=Number(current.length||15),fps=24;if(!can.captureStream||!window.MediaRecorder){toast('This browser cannot render video. Use edit pack.');return}let stream=can.captureStream(fps),rec=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm'}),chunks=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};let done=new Promise(r=>rec.onstop=()=>r(new Blob(chunks,{type:'video/webm'})));let vids=[];try{for(let c of timeline)vids.push(await loadVideo(c.videoUrl))}catch(e){toast('Some clips blocked rendering. Rendering fallback.')}rec.start();let start=performance.now();function frame(now){let t=Math.min((now-start)/1000,dur),top=435,bottom=120;ctx.fillStyle='#050505';ctx.fillRect(0,0,720,1280);if(vids.length){let seg=dur/vids.length,i=Math.min(vids.length-1,Math.floor(t/seg)),v=vids[i],lt=(t-i*seg)%Math.max(1,v.duration||4);try{if(Math.abs(v.currentTime-lt)>.15)v.currentTime=lt;drawCover(ctx,v,0,top,720,1280-top-bottom)}catch(e){fallback(ctx,top,bottom)}}else fallback(ctx,top,bottom);ctx.fillStyle='#030303';ctx.fillRect(0,0,720,top);ctx.fillStyle='#18f038';ctx.font='900 64px -apple-system,Segoe UI,sans-serif';ctx.textAlign='center';ctx.fillText('DID YOU KNOW?',360,86);ctx.fillStyle='white';ctx.font='900 39px -apple-system,Segoe UI,sans-serif';wrap(ctx,current.fact,360,140,660,43);ctx.fillStyle='#050505';ctx.fillRect(0,1160,720,120);ctx.fillStyle='white';ctx.font='bold 32px -apple-system,Segoe UI,sans-serif';ctx.textAlign='left';ctx.fillText('@FactPulse',92,1210);ctx.font='bold 26px -apple-system,Segoe UI,sans-serif';ctx.fillText(current.title,28,1256);if($('#progress'))$('#progress').style.width=(t/dur*100)+'%';if(t<dur)requestAnimationFrame(frame);else rec.stop()}requestAnimationFrame(frame);lastBlob=await done;let url=URL.createObjectURL(lastBlob);$('#videoOut').innerHTML='<video controls playsinline src="'+url+'"></video><a class="btn primary" href="'+url+'" download="factpulse-short.webm" style="margin-top:10px">Download video</a><button class="btn primary" id="shareVideo" type="button" style="margin-top:10px;width:100%">Share to YouTube</button><a class="btn secondary" href="https://studio.youtube.com" target="_blank" style="margin-top:10px">Open YouTube Studio</a>';$('#shareVideo').addEventListener('click',shareVideo);toast('Video rendered')}
async function shareVideo(){if(!lastBlob){toast('Render video first.');return}let file=new File([lastBlob],'factpulse-short.webm',{type:'video/webm'});try{if(navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({files:[file],title:current.title,text:current.description});toast('Choose YouTube in the share sheet.')}else toast('Download video, then upload in YouTube Studio.')}catch(e){toast('Share cancelled.')}}
function bind(){setActiveNav();if($('#factForm'))$('#factForm').addEventListener('submit',e=>{e.preventDefault();stateFromForm();location.href='clips.html'});if($('#searchClips'))$('#searchClips').addEventListener('click',()=>searchClips(false));if($('#searchMany'))$('#searchMany').addEventListener('click',()=>searchClips(true));if($('#renderBtn'))$('#renderBtn').addEventListener('click',renderVideo);if($('#downloadPack'))$('#downloadPack').addEventListener('click',()=>blobFile('factpulse-edit-pack.json',JSON.stringify(pack(),null,2),'application/json'));if($('#copyPost'))$('#copyPost').addEventListener('click',async()=>{stateFromForm();await navigator.clipboard.writeText($('#postBox').textContent);toast('Post copied')});if($('#copyPack'))$('#copyPack').addEventListener('click',async()=>{stateFromForm();await navigator.clipboard.writeText(JSON.stringify(pack(),null,2));toast('Pack copied')});if($('#pixabayKey'))$('#pixabayKey').addEventListener('input',saveState)}
loadState();bind();renderPreview();renderTimeline();renderClips();renderPost();