const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const STORE='factpulse-v15';
let st={subject:'',fact:'',scene:'',details:'',length:30,mode:'broad',pixabay:'',pexels:'',clips:[],timeline:[]},lastBlob=null;
function clean(x){return String(x||'').trim().replace(/\s+/g,' ')}
function esc(x){return String(x||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function toast(x){let e=$('#toast');if(!e)return;e.textContent=x;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function words(x){return clean(x).toLowerCase().split(/[^a-z0-9]+/).filter(w=>w.length>2&&!['the','and','for','with','that','this','from','into','about','after','before','when','what','why','how','was','were','are','his','her','their','who','has','had','have','did','does','junior'].includes(w)).slice(0,18)}
function titleCase(x){return clean(x).split(' ').map(w=>w?w[0].toUpperCase()+w.slice(1).toLowerCase():'').join(' ')}
function title(){return (titleCase(st.subject||words(st.fact).slice(0,4).join(' ')||'Fact')+' Fact').toUpperCase().slice(0,70)}
function autoSceneText(text){let t=clean(text).toLowerCase();let map=[['court','courtroom judge lawyer courthouse hearing documents'],['speech','speech podium microphone crowd'],['inventor','inventor lab electricity machine'],['science','science lab microscope experiment'],['money','money cash bank finance coins wallet'],['space','space rocket planet astronaut galaxy'],['ocean','ocean waves underwater sea'],['animal','wild animals wildlife nature close up'],['history','archive footage crowd speech old city street'],['school','students classroom books studying'],['health','hospital doctor patient medical'],['food','food cooking kitchen close up'],['technology','computer phone circuit technology'],['weather','storm rain lightning clouds'],['sports','stadium athlete sports training'],['music','microphone concert crowd stage'],['car','cars road traffic city driving']];
for(let [k,v] of map)if(t.includes(k))return v;return words(text).slice(0,7).join(' ')}
function searches(){let subject=clean(st.subject),scene=clean(st.scene)||autoSceneText(st.subject+' '+st.fact);return {exact:subject?[subject]:[],related:Array.from(new Set([subject+' '+scene,scene,words(st.fact).slice(0,6).join(' '),scene+' b roll'].map(clean).filter(Boolean))).slice(0,5)}}
function voice(){let f=clean(st.fact)||'This fact becomes easier to understand when the video shows the setting, movement, scale, and context.';return 'Did you know? '+f+' The key details are: '+(st.details||words(f).slice(0,4).join(', '))+'.'}
function save(){localStorage.setItem(STORE,JSON.stringify(st))}
function loadOld(){for(let k of ['factpulse-v15','factpulse-v14','factpulse-v13']){try{let x=JSON.parse(localStorage.getItem(k)||'{}');if(x.subject)st.subject=st.subject||x.subject;if(x.fact)st.fact=st.fact||x.fact;if(x.scene)st.scene=st.scene||x.scene;if(x.details)st.details=st.details||x.details;if(x.pixabayKey||x.key||x.pixabay)st.pixabay=x.pixabayKey||x.key||x.pixabay;if(x.pexelsKey||x.pexels)st.pexels=x.pexelsKey||x.pexels;if(x.current){st.subject=st.subject||x.current.subject||'';st.fact=st.fact||x.current.rawFact||x.current.fact||'';st.scene=st.scene||x.current.scene||x.current.query||'';st.details=st.details||x.current.numbers||''}}catch(e){}}}
function load(){try{let x=JSON.parse(localStorage.getItem(STORE)||'{}');st={...st,...x}}catch(e){}loadOld();['subject','fact','scene','details','length','licenseMode','pixabayKey','pexelsKey'].forEach(id=>{let e=$('#'+id);if(!e)return;let k={licenseMode:'mode',pixabayKey:'pixabay',pexelsKey:'pexels'}[id]||id;e.value=st[k]||e.value||''});sync(false)}
function sync(write=true){['subject','fact','scene','details','length','licenseMode','pixabayKey','pexelsKey'].forEach(id=>{let e=$('#'+id);if(!e)return;let k={licenseMode:'mode',pixabayKey:'pixabay',pexelsKey:'pexels'}[id]||id;st[k]=e.value});st.length=Math.min(45,Math.max(25,Number(st.length)||30));if(write)save();renderPlan();renderClips();renderTimeline();renderPost()}
function renderPlan(){let e=$('#searchPlan');if(!e)return;let q=searches();e.textContent=['Exact subject search:'].concat(q.exact.length?q.exact:['none']).concat(['','Related B-roll searches:'],q.related).join('\n')}
function renderPost(){let e=$('#postBox');if(!e)return;e.textContent=['TITLE: '+title(),'','VIDEO LENGTH: '+st.length+' seconds','','VOICEOVER:',voice(),'','DESCRIPTION:',title()+'\n\n'+st.fact+'\n\nKey details: '+st.details+'\n\n#shorts #facts #didyouknow','','CREDITS:',st.timeline.map(c=>c.credit+' via '+c.source+' | '+c.license+' | '+c.pageUrl).join('\n')].join('\n')}
async function wikiFill(){let subject=clean($('#subject')?$('#subject').value:st.subject);if(!subject){toast('Type a subject first.');return}toast('Getting fact and scene...');try{let sr=await fetch('https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch='+encodeURIComponent(subject)+'&format=json&origin=*');let sj=await sr.json();let hit=sj.query&&sj.query.search&&sj.query.search[0];let page=hit?hit.title:subject;let rr=await fetch('https://en.wikipedia.org/api/rest_v1/page/summary/'+encodeURIComponent(page));let data=rr.ok?await rr.json():{};let text=clean(data.extract||subject);st.subject=page;st.fact=text.split(/(?<=[.!?])\s+/).filter(Boolean).slice(0,2).join(' ')||subject+' is a topic with details, timeline, and context.';st.scene=autoSceneText(subject+' '+clean(data.description||'')+' '+st.fact);st.details=words(subject+' '+st.fact).slice(0,5).join(', ');['subject','fact','scene','details'].forEach(id=>{let e=$('#'+id);if(e)e.value=st[id]});st.clips=[];save();sync(false);toast('Auto filled.')}catch(e){toast('Auto fill failed. Type scene words manually.')}}
function isPub(l){l=clean(l).toLowerCase();return l.includes('public domain')||l.includes('cc0')||l.includes('pdm')}
function okLic(l){l=clean(l).toLowerCase();return isPub(l)||l.includes('cc by')||l.includes('pixabay')||l.includes('pexels')||l.includes('unknown')}
function textOf(c){return (c.tags+' '+c.credit+' '+c.pageUrl+' '+c.source).toLowerCase()}
function subjectMatch(c){let tok=words(st.subject);if(!tok.length)return false;let text=textOf(c);let hits=tok.filter(w=>text.includes(w)).length;return tok.length===1?hits===1:hits>=Math.min(2,tok.length)}
function sceneMatch(c){let tok=words(st.scene);if(!tok.length)return false;let text=textOf(c);let hits=tok.filter(w=>text.includes(w)).length;return hits>=Math.min(2,tok.length)}
function score(c){let text=textOf(c),s=0;words(st.subject).forEach(w=>{if(text.includes(w))s+=15});words(st.scene).forEach(w=>{if(text.includes(w))s+=4});if(c.match==='exact')s+=60;if(c.source==='Pixabay'||c.source==='Pexels')s+=8;if(c.source==='Wikimedia Commons')s+=4;if(isPub(c.license))s+=3;return s}
async function fetchTimeout(url,opt={},ms=9000){let ctrl=new AbortController(),id=setTimeout(()=>ctrl.abort(),ms);try{return await fetch(url,{...opt,signal:ctrl.signal})}finally{clearTimeout(id)}}
function classify(arr){let exact=[],rel=[];for(let c of arr){if(subjectMatch(c)){c.match='exact';exact.push(c)}else if(sceneMatch(c)){c.match='related';rel.push(c)}}let map=new Map([...exact,...rel].map(c=>[c.id,c]));st.clips=[...map.values()].sort((a,b)=>score(b)-score(a)).slice(0,1500)}
function addResults(arr){classify([...st.clips,...arr]);save();renderClips();let ex=st.clips.filter(c=>c.match==='exact').length,rl=st.clips.filter(c=>c.match==='related').length;setStatus(ex+' exact, '+rl+' related loaded')}
function setStatus(x){let e=$('#clipCount');if(e)e.textContent=x}
async function commons(q){let out=[],off=0;while(out.length<50){let r=await fetchTimeout('https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrnamespace=6&gsrlimit=50&gsroffset='+off+'&gsrsearch='+encodeURIComponent(q+' filetype:video')+'&prop=imageinfo&iiprop=url|mime|extmetadata&format=json&origin=*',{},8000);if(!r.ok)break;let j=await r.json(),pages=j.query&&j.query.pages?Object.values(j.query.pages):[];pages.forEach(p=>{let ii=p.imageinfo&&p.imageinfo[0];if(!ii||!String(ii.mime||'').startsWith('video/'))return;let m=ii.extmetadata||{},lic=(m.LicenseShortName&&m.LicenseShortName.value)||(m.UsageTerms&&m.UsageTerms.value)||'Unknown license';if(st.mode==='public'&&!isPub(lic))return;if(st.mode!=='public'&&!okLic(lic))return;out.push({id:'commons-'+p.pageid,source:'Wikimedia Commons',credit:(m.Artist&&m.Artist.value?m.Artist.value.replace(/<[^>]+>/g,''):'Wikimedia contributor'),pageUrl:'https://commons.wikimedia.org/wiki/'+encodeURIComponent(p.title.replaceAll(' ','_')),videoUrl:ii.url,previewUrl:ii.url,tags:p.title+' '+q,license:lic})});if(!j.continue||!j.continue.gsroffset)break;off=j.continue.gsroffset}return out}
async function pixabay(q,many){if(!st.pixabay||st.mode==='public')return[];let all=[],pages=many?5:1;for(let p=1;p<=pages;p++){let r=await fetchTimeout('https://pixabay.com/api/videos/?key='+encodeURIComponent(st.pixabay)+'&q='+encodeURIComponent(q)+'&orientation=vertical&per_page='+(many?200:40)+'&page='+p+'&safesearch=true&order=popular',{},8000);if(!r.ok)break;let j=await r.json();(j.hits||[]).forEach(v=>{let f=v.videos&&((v.videos.medium)||(v.videos.small)||(v.videos.large)||(v.videos.tiny));if(f&&f.url)all.push({id:'pixabay-'+v.id,source:'Pixabay',credit:v.user||'Pixabay creator',pageUrl:v.pageURL,videoUrl:f.url,previewUrl:f.url,tags:v.tags||q,license:'Pixabay Content License'})})}return all}
async function pexels(q,many){if(!st.pexels||st.mode==='public')return[];let all=[],pages=many?8:1;for(let p=1;p<=pages;p++){let r=await fetchTimeout('https://api.pexels.com/videos/search?query='+encodeURIComponent(q)+'&orientation=portrait&size=medium&per_page='+(many?80:40)+'&page='+p,{headers:{Authorization:st.pexels}},8000);if(!r.ok)break;let j=await r.json();(j.videos||[]).forEach(v=>{let f=(v.video_files||[]).filter(x=>x.link&&x.height>=x.width)[0]||(v.video_files||[])[0];if(f&&f.link)all.push({id:'pexels-'+v.id,source:'Pexels',credit:v.user&&v.user.name||'Pexels creator',pageUrl:v.url,videoUrl:f.link,previewUrl:f.link,tags:q,license:'Pexels License'})})}return all}
async function searchClips(many){sync();st.clips=[];renderClips();let q=searches();let runs=[...q.exact.map(x=>['exact',x]),...q.related.map(x=>['related',x])];setStatus('Starting strict search...');for(let [kind,term] of runs){let sources=[['Wikimedia',commons]];if(st.mode!=='public'){if(st.pixabay)sources.unshift(['Pixabay',pixabay]);if(st.pexels)sources.unshift(['Pexels',pexels])}for(let [name,fn] of sources){try{setStatus('Searching '+name+': '+term);let res=await fn(term,many);if(res.length)addResults(res)}catch(e){}}}
let ex=st.clips.filter(c=>c.match==='exact').length,rl=st.clips.filter(c=>c.match==='related').length;setStatus(ex+' exact, '+rl+' related loaded');toast(st.clips.length?'Strict search finished.':'No relevant clips found. Add better scene words or a stock key.')}
function addClip(i){let c=st.clips[i];if(!c)return;st.timeline.push(c);save();renderTimeline();renderPost();toast('Clip added')}
function modal(){if($('#clipModal))return;let d=document.createElement('div');d.id='clipModal';d.innerHTML='<div class="modal-card"><button class="modal-close" id="closeModal" type="button">×</button><video id="modalVideo" controls playsinline></video><div class="box" id="modalInfo"></div><div class="two"><button class="btn primary" id="modalAdd" type="button">Add clip</button><a class="btn secondary" id="modalSource" target="_blank">Source</a></div></div>';document.body.appendChild(d);$('#closeModal').onclick=closePreview;d.onclick=e=>{if(e.target.id==='clipModal')closePreview()}}
function openPreview(i){let c=st.clips[i];if(!c)return;modal();$('#modalVideo').src=c.videoUrl;$('#modalVideo').play().catch(()=>{});$('#modalInfo').textContent=(c.match==='exact'?'Exact subject match':'Related B-roll')+'\n'+c.source+'\nLicense: '+c.license+'\nTopic: '+c.tags;$('#modalSource').href=c.pageUrl;$('#modalAdd').onclick=()=>{addClip(i);closePreview()};$('#clipModal').classList.add('show')}
function closePreview(){let v=$('#modalVideo'),m=$('#clipModal');if(v){v.pause();v.removeAttribute('src')}if(m)m.classList.remove('show')}
function renderClips(){let g=$('#clipGrid');if(!g)return;if($('#clipCount')&&!st.clips.length)$('#clipCount').textContent='0 clips loaded';g.innerHTML='';if(!st.clips.length){g.innerHTML='<div class="box">No clips loaded. Exact clips must contain your subject. Related B-roll must match your scene words. Random archive footage is off.</div>';return}let groups=[['EXACT TOPIC',st.clips.filter(c=>c.match==='exact')],['RELATED B-ROLL',st.clips.filter(c=>c.match==='related')]];groups.forEach(([label,list])=>{if(!list.length)return;let h=document.createElement('div');h.className='box';h.textContent=label+' · '+list.length+' clips';g.appendChild(h);list.forEach(c=>{let i=st.clips.indexOf(c),el=document.createElement('article');el.className='clip';el.innerHTML='<div class="thumb"><video muted playsinline preload="metadata" src="'+c.previewUrl+'"></video></div><strong>'+label+' · '+esc(c.source)+'</strong><small>License: '+esc(c.license)+'</small><small>Topic: '+esc((c.tags||'').slice(0,100))+'</small><div class="row"><button type="button" data-p="'+i+'">Preview</button><button type="button" data-a="'+i+'">Add</button></div><a href="'+c.pageUrl+'" target="_blank">Source</a>';g.appendChild(el)})});g.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>openPreview(Number(b.dataset.p)));g.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>addClip(Number(b.dataset.a)));g.querySelectorAll('.clip').forEach(card=>card.onclick=e=>{if(!e.target.closest('button,a')){let b=card.querySelector('[data-p]');if(b)openPreview(Number(b.dataset.p))}})}
function renderTimeline(){let e=$('#timeline');if(!e)return;if($('#timelineCount'))$('#timelineCount').textContent=st.timeline.length+' clips selected. Final length: '+st.length+' seconds.';e.innerHTML=st.timeline.length?'':'<div class="box">No clips added yet.</div>';st.timeline.forEach((c,i)=>{let d=document.createElement('div');d.className='item';d.innerHTML='<div><strong>Clip '+(i+1)+' · '+esc(c.source)+'</strong><small>'+esc(c.license)+'</small><small>'+esc(c.pageUrl)+'</small></div><button type="button" data-rm="'+i+'">×</button>';e.appendChild(d)});e.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{st.timeline.splice(Number(b.dataset.rm),1);save();renderTimeline();renderPost()})}
function wrap(ctx,t,x,y,w,lh,max){let arr=t.split(' '),line='',lines=[];for(let a of arr){let test=line+a+' ';if(ctx.measureText(test).width>w&&line){lines.push(line.trim());line=a+' '}else line=test}lines.push(line.trim());lines.slice(0,max).forEach((l,i)=>ctx.fillText(l,x,y+i*lh))}
function draw(ctx,v,x,y,w,h){let vw=v.videoWidth||720,vh=v.videoHeight||1280,s=Math.max(w/vw,h/vh),sw=w/s,sh=h/s;ctx.drawImage(v,(vw-sw)/2,(vh-sh)/2,sw,sh,x,y,w,h)}
function loadVid(src){return new Promise((res,rej)=>{let v=document.createElement('video');v.crossOrigin='anonymous';v.muted=true;v.playsInline=true;v.src=src;v.onloadeddata=()=>res(v);v.onerror=rej})}
async function renderVideo(){sync();let can=$('#canvas'),ctx=can.getContext('2d'),dur=st.length;if(!can.captureStream||!window.MediaRecorder){toast('This browser cannot render video.');return}let vids=[];try{for(let c of st.timeline)vids.push(await loadVid(c.videoUrl))}catch(e){}let rec=new MediaRecorder(can.captureStream(24),{mimeType:MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm'}),chunks=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};let done=new Promise(r=>rec.onstop=()=>r(new Blob(chunks,{type:'video/webm'})));rec.start();let start=performance.now();function frame(now){let t=Math.min((now-start)/1000,dur),top=430,bottom=110;ctx.fillStyle='#050505';ctx.fillRect(0,0,720,1280);if(vids.length){let i=Math.min(vids.length-1,Math.floor(t/(dur/vids.length))),v=vids[i];try{v.currentTime=(t%(Math.max(v.duration||4,1)));draw(ctx,v,0,top,720,1280-top-bottom)}catch(e){}}else{ctx.fillStyle='#1f6fb6';ctx.fillRect(0,top,720,1280-top-bottom)}ctx.fillStyle='#030303';ctx.fillRect(0,0,720,top);ctx.fillStyle='#18f038';ctx.font='900 56px -apple-system,Segoe UI,sans-serif';ctx.textAlign='center';ctx.fillText('DID YOU KNOW?',360,82);ctx.fillStyle='white';ctx.font='900 35px -apple-system,Segoe UI,sans-serif';wrap(ctx,st.fact,360,137,660,39,7);ctx.fillStyle='#050505';ctx.fillRect(0,1170,720,110);ctx.fillStyle='white';ctx.font='bold 29px -apple-system,Segoe UI,sans-serif';ctx.textAlign='left';ctx.fillText('@FactPulse',28,1215);ctx.font='bold 25px -apple-system,Segoe UI,sans-serif';ctx.fillText(title().slice(0,38),28,1256);if($('#progress'))$('#progress').style.width=(t/dur*100)+'%';if(t<dur)requestAnimationFrame(frame);else rec.stop()}requestAnimationFrame(frame);lastBlob=await done;let url=URL.createObjectURL(lastBlob);$('#videoOut').innerHTML='<video controls playsinline src="'+url+'"></video><a class="btn primary" href="'+url+'" download="factpulse-short.webm" style="margin-top:10px">Download styled video</a>';toast('Styled video rendered')}
function pack(){sync();return{title:title(),voiceover:voice(),description:st.fact,clips:st.timeline}}
function blobFile(name,content,type){let b=new Blob([content],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
function inject(){if($('#modalStyle'))return;let s=document.createElement('style');s.id='modalStyle';s.textContent='#clipModal{position:fixed;inset:0;z-index:200;background:rgba(0,0,0,.86);display:none;align-items:center;justify-content:center;padding:14px}#clipModal.show{display:flex}.modal-card{width:min(96vw,430px);max-height:92vh;overflow:auto;background:#111318;border:1px solid #2a2e38;border-radius:24px;padding:12px}.modal-card video{width:100%;max-height:58vh;background:#000;border-radius:18px}.modal-close{float:right;border:0;border-radius:999px;background:#18f038;color:#051007;font-weight:1000;width:40px;height:40px}.clip{cursor:pointer}.clip>a{display:block;margin-top:0}';document.head.appendChild(s)}
function bind(){inject();$$('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===(document.body.dataset.page||'create')));if($('#factForm'))$('#factForm').onsubmit=e=>{e.preventDefault();sync();st.clips=[];save();location.href='clips-v15.html'};if($('#autoFill'))$('#autoFill').onclick=wikiFill;if($('#searchClips'))$('#searchClips').onclick=()=>searchClips(false);if($('#searchMany'))$('#searchMany').onclick=()=>searchClips(true);if($('#renderBtn'))$('#renderBtn').onclick=renderVideo;if($('#copyPost'))$('#copyPost').onclick=async()=>{sync();await navigator.clipboard.writeText($('#postBox').textContent);toast('Copied')};if($('#downloadPack'))$('#downloadPack').onclick=()=>blobFile('factpulse-edit-pack.json',JSON.stringify(pack(),null,2),'application/json');['subject','fact','scene','details','length','licenseMode','pixabayKey','pexelsKey'].forEach(id=>{let e=$('#'+id);if(e)e.addEventListener('input',()=>{st.clips=[];sync()});if(e&&id==='licenseMode')e.addEventListener('change',()=>{st.clips=[];sync()})})}
load();bind();renderPlan();renderClips();renderTimeline();renderPost();