const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
let current={},clips=[],timeline=[],lastBlob=null;
const STORE='factpulse-v10',OLD=['factpulse-v9','factpulse-v8','factpulse-v7','factpulse-v6','factpulse-v5','factpulse-v4'];
const DEFAULT_QUERY='civil rights speech crowd';
function clean(t){return String(t||'').trim().replace(/\s+/g,' ')}
function esc(t){return String(t).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function toast(t){let e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function setActiveNav(){let p=document.body.dataset.page||'create';$$('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===p))}
function words(q){return clean(q).toLowerCase().split(/[^a-z0-9]+/).filter(w=>w.length>2).slice(0,12)}
function titleCase(s){return clean(s).split(' ').map(w=>w?w[0].toUpperCase()+w.slice(1).toLowerCase():'').join(' ')}
function topic(q){let w=words(q).slice(0,4).join(' ');return titleCase(w||'This Topic')}
function titleFrom(q){return topic(q).toUpperCase()+' FACT'}
function factFrom(q,tags){let t=topic(tags||q);return t+' looks simple at first, but the real value is in the details you can see on screen: the setting, movement, scale, and context.'}
function proofFrom(q,tags){let t=words(tags||q).slice(0,3);return (t.length?t.join(', '):'setting, movement, context')}
function nums(){let v=$('#numbers')?$('#numbers').value:current.numbers;return clean(v).split(',').map(x=>x.trim()).filter(Boolean)}
function replace1(text,search,repl){let i=text.toLowerCase().indexOf(search.toLowerCase());return i<0?text:text.slice(0,i)+repl+text.slice(i+search.length)}
function overlay(f,q){let h=esc(f);nums().slice(0,3).forEach((n,i)=>h=replace1(h,esc(n),'<mark class="'+(i==1?'yellow':i==2?'blue':'')+'">'+esc(n)+'</mark>'));words(q).slice(0,2).forEach((w,i)=>{if(h.toLowerCase().includes(w))h=replace1(h,w,'<mark class="'+(i?'blue':'')+'">'+esc(w)+'</mark>')});return h}
function voice(f){let ns=nums();return 'Did you know? '+f+' '+(ns.length?'The key details are: '+ns.join(', ')+'.':'The detail is easy to miss.')+' That is why this clip works as a short video.'}
function cap(t){return t.replace(/([.!?])\s+/g,'$1|').split('|').filter(Boolean).map(s=>{let w=s.split(' ');if(w.length<=7)return s;let a=[];for(let i=0;i<w.length;i+=7)a.push(w.slice(i,i+7).join(' '));return a.join('\n')})}
function loadField(name){for(let k of [STORE,...OLD]){try{let s=localStorage.getItem(k);if(s){let st=JSON.parse(s);if(st[name])return st[name]}}catch(e){}}return ''}
function save(){try{localStorage.setItem(STORE,JSON.stringify({current,clips,timeline,pixabayKey:$('#pixabayKey')?$('#pixabayKey').value:loadField('pixabayKey'),pexelsKey:$('#pexelsKey')?$('#pexelsKey').value:loadField('pexelsKey'),licenseMode:$('#licenseMode')?$('#licenseMode').value:current.licenseMode||'broad'}))}catch(e){}}
function rebuild(){let q=$('#query')?clean($('#query').value):(current.query||DEFAULT_QUERY);let len=$('#length')?Number($('#length').value):Number(current.length||30);len=Math.max(25,len||30);let f=$('#fact')?clean($('#fact').value):(current.fact||factFrom(q,current.captionTopic));let n=$('#numbers')?clean($('#numbers').value):(current.numbers||proofFrom(q,current.captionTopic));let vo=voice(f);current={...current,query:q,fact:f,numbers:n,length:len,title:titleFrom(current.captionTopic||q),overlay:overlay(f,current.captionTopic||q),overlayPlain:'DID YOU KNOW?\n'+f+(n?'\nKey details: '+n:''),voiceover:vo,captions:cap(vo),description:titleFrom(current.captionTopic||q)+'\n\n'+f+'\n\n'+(n?'Key details: '+n+'\n\n':'')+'#shorts #didyouknow #facts #interestingfacts',licenseMode:$('#licenseMode')?$('#licenseMode').value:(current.licenseMode||'broad')};save();renderAll()}
function setCaption(q,tags){let t=tags||q;current.captionTopic=t;current.fact=factFrom(q,t);current.numbers=proofFrom(q,t);if($('#fact'))$('#fact').value=current.fact;if($('#numbers'))$('#numbers').value=current.numbers}
function load(){let raw=null;for(let k of [STORE,...OLD]){raw=localStorage.getItem(k);if(raw)break}if(raw){try{let st=JSON.parse(raw);current=st.current||{};clips=st.clips||[];timeline=st.timeline||[];if($('#pixabayKey'))$('#pixabayKey').value=st.pixabayKey||st.key||'';if($('#pexelsKey'))$('#pexelsKey').value=st.pexelsKey||'';if($('#licenseMode'))$('#licenseMode').value=st.licenseMode||current.licenseMode||'broad'}catch(e){}}
if(!current.query)current.query=DEFAULT_QUERY;if(!current.fact)setCaption(current.query,current.query);if($('#query'))$('#query').value=current.query;if($('#fact'))$('#fact').value=current.fact;if($('#numbers'))$('#numbers').value=current.numbers;if($('#length'))$('#length').value=String(Math.max(25,Number(current.length||30)));if($('#pixabayKey')&&!$('#pixabayKey').value)$('#pixabayKey').value=loadField('pixabayKey')||loadField('key');if($('#pexelsKey')&&!$('#pexelsKey').value)$('#pexelsKey').value=loadField('pexelsKey');rebuild()}
function renderAll(){renderPreview();renderPost();renderClips();renderTimeline()}
function renderPreview(){let pt=$('#previewText'),tt=$('#previewTitle');if(pt)pt.innerHTML=current.overlay||overlay(current.fact,current.query);if(tt)tt.textContent=current.title||titleFrom(current.query);let bg=$('#clipBg'),pv=$('#previewVideo'),first=timeline[0];if(bg&&pv&&first){pv.src=first.videoUrl;bg.classList.add('on');pv.play().catch(()=>{})}else if(bg)bg.classList.remove('on')}
function renderPost(){let box=$('#postBox');if(!box)return;box.textContent=['TITLE: '+(current.title||''),'','VIDEO LENGTH: '+Math.max(25,Number(current.length||30))+' seconds','','LICENSE MODE: '+(current.licenseMode==='public'?'Public domain / CC0 focus':'Public domain, CC, and royalty-free stock'),'','VOICEOVER:',current.voiceover||'','','CAPTIONS:',(current.captions||[]).join('\n\n'),'','DESCRIPTION:',current.description||'','','CREDITS:',timeline.map(c=>c.credit+' via '+c.source+' | '+c.license+' | '+c.pageUrl).join('\n')].join('\n')}
function isPublicLicense(x){x=clean(x).toLowerCase();return x.includes('public domain')||x.includes('cc0')||x.includes('pdm')}
function isPermissiveLicense(x){x=clean(x).toLowerCase();return isPublicLicense(x)||x.includes('cc by')||x.includes('creative commons attribution')||x.includes('cc-by')||x.includes('pixabay')||x.includes('pexels')}
function score(c,ts){let text=(c.tags+' '+c.credit+' '+c.pageUrl+' '+c.license).toLowerCase();let s=0;ts.forEach(t=>{if(text.includes(t))s+=3});if(c.source==='Wikimedia Commons')s+=2;if(c.source==='Internet Archive')s+=2;if(isPublicLicense(c.license))s+=3;if(c.duration>=25)s+=1;return s}
async function searchCommons(q,many,mode){let limit=many?500:60,all=[],cont=null;while(all.length<limit){let params='https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrnamespace=6&gsrlimit=50&gsrsearch='+encodeURIComponent(q+' filetype:video')+'&prop=imageinfo&iiprop=url|mime|extmetadata&format=json&origin=*';if(cont)params+='&gsroffset='+encodeURIComponent(cont);let r=await fetch(params);if(!r.ok)break;let j=await r.json();let pages=j.query&&j.query.pages?Object.values(j.query.pages):[];pages.forEach(p=>{let ii=p.imageinfo&&p.imageinfo[0];if(!ii||!ii.url||!(ii.mime||'').startsWith('video/'))return;let meta=ii.extmetadata||{};let lic=(meta.LicenseShortName&&meta.LicenseShortName.value)||(meta.UsageTerms&&meta.UsageTerms.value)||'Unknown license';let allowed=mode==='public'?isPublicLicense(lic):isPermissiveLicense(lic);if(!allowed)return;let name=(p.title||'File').replace(/^File:/,'');all.push({id:'commons-'+p.pageid,source:'Wikimedia Commons',credit:(meta.Artist&&meta.Artist.value?meta.Artist.value.replace(/<[^>]+>/g,''):'Wikimedia contributor'),pageUrl:'https://commons.wikimedia.org/wiki/'+encodeURIComponent(p.title.replaceAll(' ','_')),videoUrl:ii.url,previewUrl:ii.url,duration:0,tags:name+' '+q,license:lic})});if(!j.continue||!j.continue.gsroffset)break;cont=j.continue.gsroffset}return all}
async function searchArchive(q,many,mode){let rows=many?1000:80;let url='https://archive.org/advancedsearch.php?q='+encodeURIComponent(q+' AND mediatype:movies')+'&fl[]=identifier&fl[]=title&fl[]=description&fl[]=licenseurl&fl[]=rights&rows='+rows+'&page=1&output=json';let r=await fetch(url);if(!r.ok)return[];let j=await r.json(),docs=(j.response&&j.response.docs)||[],out=[];let usable=docs.filter(d=>{let lic=(d.licenseurl||'')+' '+(d.rights||'');return mode==='public'?isPublicLicense(lic):isPermissiveLicense(lic)||lic==='' }).slice(0,many?120:40);for(let d of usable){try{let m=await fetch('https://archive.org/metadata/'+encodeURIComponent(d.identifier));if(!m.ok)continue;let meta=await m.json();let file=(meta.files||[]).find(f=>/\.mp4$/i.test(f.name)&&!String(f.name).toLowerCase().includes('thumb'));if(!file)continue;let lic=(d.licenseurl||meta.metadata&&meta.metadata.licenseurl||d.rights||'verify source rights');if(mode==='public'&&!isPublicLicense(lic))continue;out.push({id:'archive-'+d.identifier+'-'+file.name,source:'Internet Archive',credit:d.title||d.identifier,pageUrl:'https://archive.org/details/'+d.identifier,videoUrl:'https://archive.org/download/'+d.identifier+'/'+encodeURIComponent(file.name),previewUrl:'https://archive.org/download/'+d.identifier+'/'+encodeURIComponent(file.name),duration:Math.round(Number(file.length||0))||0,tags:(d.title||q)+' '+(d.description||''),license:lic})}catch(e){}}return out}
async function searchPixabay(q,key,many,mode){if(!key||mode==='public')return[];let pages=many?5:1,per=many?200:40,all=[];for(let p=1;p<=pages;p++){let url='https://pixabay.com/api/videos/?key='+encodeURIComponent(key)+'&q='+encodeURIComponent(q)+'&orientation=vertical&per_page='+per+'&page='+p+'&safesearch=true&order=popular';let r=await fetch(url);if(!r.ok)break;let j=await r.json();(j.hits||[]).forEach(v=>{let file=v.videos&&((v.videos.medium)||(v.videos.small)||(v.videos.large)||(v.videos.tiny));if(file&&file.url)all.push({id:'pixabay-'+v.id,source:'Pixabay',credit:v.user||'Pixabay creator',pageUrl:v.pageURL,videoUrl:file.url,previewUrl:file.url,duration:v.duration||0,tags:v.tags||q,license:'Pixabay Content License'})})}return all}
async function searchPexels(q,key,many,mode){if(!key||mode==='public')return[];let pages=many?13:1,per=many?80:40,all=[];for(let p=1;p<=pages;p++){let url='https://api.pexels.com/videos/search?query='+encodeURIComponent(q)+'&orientation=portrait&size=medium&per_page='+per+'&page='+p;let r=await fetch(url,{headers:{Authorization:key}});if(!r.ok)break;let j=await r.json();(j.videos||[]).forEach(v=>{let file=(v.video_files||[]).filter(f=>f.link&&f.height>=f.width).sort((a,b)=>Math.abs(a.height-1280)-Math.abs(b.height-1280))[0]||(v.video_files||[])[0];if(file&&file.link)all.push({id:'pexels-'+v.id,source:'Pexels',credit:v.user&&v.user.name||'Pexels creator',pageUrl:v.url,videoUrl:file.link,previewUrl:file.link,duration:v.duration||0,tags:q+' '+(v.user&&v.user.name||''),license:'Pexels License'})})}return all}
async function searchClips(many){let q=$('#query')?clean($('#query').value):(current.query||DEFAULT_QUERY);current.query=q;setCaption(q,q);rebuild();let mode=$('#licenseMode')?$('#licenseMode').value:(current.licenseMode||'broad');let pix=clean($('#pixabayKey')?$('#pixabayKey').value:''),pex=clean($('#pexelsKey')?$('#pexelsKey').value:'');clips=[];current.lastSearched=true;renderClips();$('#clipCount').textContent='Scanning internet video sources for: '+q;try{let jobs=[searchCommons(q,many,mode),searchArchive(q,many,mode),searchPixabay(q,pix,many,mode),searchPexels(q,pex,many,mode)];let settled=await Promise.allSettled(jobs),results=[];settled.forEach(x=>{if(x.status==='fulfilled')results.push(...x.value)});let ts=words(q);results.sort((a,b)=>score(b,ts)-score(a,ts));clips=Array.from(new Map(results.map(c=>[c.id,c])).values()).slice(0,many?2000:100);save();renderClips();$('#clipCount').textContent=clips.length+' clips loaded from internet sources for: '+q;if(!clips.length)toast('No clips found. Try Broad mode, add a stock API key, or use simpler search words.');else toast(clips.length+' clips loaded')}catch(e){$('#clipCount').textContent='Search failed';toast('Search failed. Try broader search words.')}}
function addClip(i){let c=clips[i];if(!c)return;timeline.push(c);setCaption(current.query,c.tags||current.query);rebuild();toast('Clip added. Caption updated.')}
function ensurePreviewModal(){if($('#clipModal'))return;let d=document.createElement('div');d.id='clipModal';d.innerHTML='<div class="modal-card"><button class="modal-close" id="closeModal" type="button">×</button><video id="modalVideo" controls playsinline></video><div class="box" id="modalInfo"></div><div class="two"><button class="btn primary" id="modalAdd" type="button">Add clip</button><a class="btn secondary" id="modalSource" target="_blank">Source</a></div></div>';document.body.appendChild(d);$('#closeModal').onclick=closePreview;d.addEventListener('click',e=>{if(e.target.id==='clipModal')closePreview()})}
function openPreview(i){let c=clips[i];if(!c)return;ensurePreviewModal();let v=$('#modalVideo');v.src=c.videoUrl;v.play().catch(()=>{});$('#modalInfo').textContent=(c.source+'\nLicense: '+(c.license||'verify source')+'\nTopic: '+(c.tags||current.query)+'\nLength: '+(c.duration?c.duration+' sec':'unknown'));$('#modalSource').href=c.pageUrl;$('#modalAdd').onclick=()=>{addClip(i);closePreview()};$('#clipModal').classList.add('show')}
function closePreview(){let m=$('#clipModal'),v=$('#modalVideo');if(v){v.pause();v.removeAttribute('src')}if(m)m.classList.remove('show')}
function renderClips(){let g=$('#clipGrid');if(!g)return;if($('#clipCount'))$('#clipCount').textContent=clips.length?clips.length+' clips loaded':'0 clips loaded';g.innerHTML='';if(!clips.length){let msg=current.lastSearched?'No clips found for this search. Try Broad legal sources, add Pixabay or Pexels keys, or use simpler words like crowd, ocean, city, factory, storm, rocket.':'No clips loaded yet. Tap Find legal clips or Search thousands. Tap a clip afterward to preview the video.';g.innerHTML='<div class="box">'+msg+'</div>';return}clips.forEach((c,i)=>{let el=document.createElement('article');el.className='clip';el.dataset.i=i;el.innerHTML='<div class="thumb"><video muted playsinline preload="metadata" src="'+c.previewUrl+'"></video></div><strong>'+esc(c.source)+' clip '+(i+1)+'</strong><small>License: '+esc(c.license||'verify source')+'</small><small>Topic: '+esc((c.tags||'related clip').slice(0,100))+'</small><small>'+(c.duration?c.duration+' sec source clip':'duration unknown')+'</small><div class="row"><button type="button" data-preview="'+i+'">Preview</button><button type="button" data-add="'+i+'">Add</button></div><a href="'+c.pageUrl+'" target="_blank">Source</a>';g.appendChild(el)});g.querySelectorAll('[data-add]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();addClip(Number(b.dataset.add))}));g.querySelectorAll('[data-preview]').forEach(b=>b.addEventListener('click',e=>{e.stopPropagation();openPreview(Number(b.dataset.preview))}));g.querySelectorAll('.clip').forEach(card=>{let v=card.querySelector('.thumb video');card.addEventListener('touchstart',()=>v&&v.play().catch(()=>{}),{passive:true});card.addEventListener('click',e=>{if(e.target.closest('a,button'))return;openPreview(Number(card.dataset.i))})})}
function renderTimeline(){let e=$('#timeline');if(!e)return;if($('#timelineCount'))$('#timelineCount').textContent=timeline.length+' clips selected. Final length: '+Math.max(25,Number(current.length||30))+' seconds.';e.innerHTML='';if(!timeline.length){e.innerHTML='<div class="box">No clips added yet. Go to Clips and tap a video card.</div>';return}timeline.forEach((c,i)=>{let it=document.createElement('div');it.className='item';it.innerHTML='<div><strong>Clip '+(i+1)+' - '+esc(c.source)+'</strong><small>'+esc(c.license||'verify source')+'</small><small>'+esc(c.pageUrl)+'</small></div><button type="button" data-rm="'+i+'">×</button>';e.appendChild(it)});e.querySelectorAll('[data-rm]').forEach(b=>b.addEventListener('click',()=>{timeline.splice(Number(b.dataset.rm),1);save();renderAll()}))}
function blobFile(name,content,type){let blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function pack(){rebuild();return{title:current.title,fact:current.fact,overlay:current.overlayPlain,lengthSeconds:Math.max(25,Number(current.length||30)),searchQuery:current.query,licenseMode:current.licenseMode,voiceover:current.voiceover,captions:current.captions,description:current.description,selectedClips:timeline.map(c=>({source:c.source,creator:c.credit,pageUrl:c.pageUrl,videoUrl:c.videoUrl,tags:c.tags,duration:c.duration,license:c.license}))}}
function loadVideo(src){return new Promise((res,rej)=>{let v=document.createElement('video');v.crossOrigin='anonymous';v.muted=true;v.playsInline=true;v.src=src;v.preload='auto';v.onloadeddata=()=>res(v);v.onerror=rej})}
function drawCover(ctx,v,x,y,w,h){let vw=v.videoWidth||720,vh=v.videoHeight||1280,sc=Math.max(w/vw,h/vh),sw=w/sc,sh=h/sc,sx=(vw-sw)/2,sy=(vh-sh)/2;ctx.drawImage(v,sx,sy,sw,sh,x,y,w,h)}
function wrap(ctx,t,x,y,w,lh){let words=t.split(' '),line='';ctx.textAlign='center';for(let n=0;n<words.length;n++){let test=line+words[n]+' ';if(ctx.measureText(test).width>w&&n>0){ctx.fillText(line.trim(),x,y);line=words[n]+' ';y+=lh}else line=test}ctx.fillText(line.trim(),x,y)}
function fallback(ctx,top,bottom){let g=ctx.createLinearGradient(0,top,720,1280-bottom);g.addColorStop(0,'#79c5ff');g.addColorStop(.5,'#3189d5');g.addColorStop(1,'#095b9a');ctx.fillStyle=g;ctx.fillRect(0,top,720,1280-top-bottom)}
async function renderVideo(){rebuild();let can=$('#canvas'),ctx=can.getContext('2d'),dur=Math.max(25,Number(current.length||30)),fps=24;if(!can.captureStream||!window.MediaRecorder){toast('This browser cannot render video. Use edit pack.');return}let stream=can.captureStream(fps),rec=new MediaRecorder(stream,{mimeType:MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm'}),chunks=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};let done=new Promise(r=>rec.onstop=()=>r(new Blob(chunks,{type:'video/webm'})));let vids=[];try{for(let c of timeline)vids.push(await loadVideo(c.videoUrl))}catch(e){toast('Some clips blocked browser rendering. Rendering fallback.')}rec.start();let start=performance.now();function frame(now){let t=Math.min((now-start)/1000,dur),top=435,bottom=120;ctx.fillStyle='#050505';ctx.fillRect(0,0,720,1280);if(vids.length){let seg=dur/vids.length,i=Math.min(vids.length-1,Math.floor(t/seg)),v=vids[i],lt=(t-i*seg)%Math.max(1,v.duration||4);try{if(Math.abs(v.currentTime-lt)>.15)v.currentTime=lt;drawCover(ctx,v,0,top,720,1280-top-bottom)}catch(e){fallback(ctx,top,bottom)}}else fallback(ctx,top,bottom);ctx.fillStyle='#030303';ctx.fillRect(0,0,720,top);ctx.fillStyle='#18f038';ctx.font='900 64px -apple-system,Segoe UI,sans-serif';ctx.textAlign='center';ctx.fillText('DID YOU KNOW?',360,86);ctx.fillStyle='white';ctx.font='900 39px -apple-system,Segoe UI,sans-serif';wrap(ctx,current.fact,360,140,660,43);ctx.fillStyle='#050505';ctx.fillRect(0,1160,720,120);ctx.fillStyle='white';ctx.font='bold 32px -apple-system,Segoe UI,sans-serif';ctx.textAlign='left';ctx.fillText('@FactPulse',92,1210);ctx.font='bold 26px -apple-system,Segoe UI,sans-serif';ctx.fillText(current.title,28,1256);if($('#progress'))$('#progress').style.width=(t/dur*100)+'%';if(t<dur)requestAnimationFrame(frame);else rec.stop()}requestAnimationFrame(frame);lastBlob=await done;let url=URL.createObjectURL(lastBlob);$('#videoOut').innerHTML='<video controls playsinline src="'+url+'"></video><a class="btn primary" href="'+url+'" download="factpulse-short.webm" style="margin-top:10px">Download 25+ second video</a><button class="btn primary" id="shareVideo" type="button" style="margin-top:10px;width:100%">Share to YouTube</button><a class="btn secondary" href="https://studio.youtube.com" target="_blank" style="margin-top:10px">Open YouTube Studio</a>';$('#shareVideo').addEventListener('click',shareVideo);toast('Video rendered. Length: '+dur+' seconds')}
async function shareVideo(){if(!lastBlob){toast('Render video first.');return}let file=new File([lastBlob],'factpulse-short.webm',{type:'video/webm'});try{if(navigator.canShare&&navigator.canShare({files:[file]})){await navigator.share({files:[file],title:current.title,text:current.description});toast('Choose YouTube in the share sheet.')}else toast('Download video, then upload in YouTube Studio.')}catch(e){toast('Share cancelled.')}}
function injectModalStyle(){if($('#modalStyle'))return;let style=document.createElement('style');style.id='modalStyle';style.textContent='#clipModal{position:fixed;inset:0;z-index:200;background:rgba(0,0,0,.86);display:none;align-items:center;justify-content:center;padding:14px}#clipModal.show{display:flex}.modal-card{width:min(96vw,430px);max-height:92vh;overflow:auto;background:#111318;border:1px solid #2a2e38;border-radius:24px;padding:12px;box-shadow:0 24px 70px rgba(0,0,0,.7)}.modal-card video{width:100%;max-height:58vh;background:#000;border-radius:18px;border:1px solid #2a2e38}.modal-close{float:right;margin-bottom:8px;border:0;border-radius:999px;background:#18f038;color:#051007;font-weight:1000;width:40px;height:40px}.clip{cursor:pointer}.clip .row{grid-template-columns:1fr 1fr}.clip>a{display:block;margin-top:0}';document.head.appendChild(style)}
function bind(){injectModalStyle();setActiveNav();if($('#factForm'))$('#factForm').addEventListener('submit',e=>{e.preventDefault();rebuild();location.href='clips-v10.html'});if($('#query'))$('#query').addEventListener('input',()=>{let q=clean($('#query').value);current.query=q;setCaption(q,q);rebuild()});if($('#searchClips'))$('#searchClips').addEventListener('click',()=>searchClips(false));if($('#searchMany'))$('#searchMany').addEventListener('click',()=>searchClips(true));if($('#licenseMode'))$('#licenseMode').addEventListener('change',()=>{current.licenseMode=$('#licenseMode').value;save()});if($('#renderBtn'))$('#renderBtn').addEventListener('click',renderVideo);if($('#downloadPack'))$('#downloadPack').addEventListener('click',()=>blobFile('factpulse-edit-pack.json',JSON.stringify(pack(),null,2),'application/json'));if($('#copyPost'))$('#copyPost').addEventListener('click',async()=>{rebuild();await navigator.clipboard.writeText($('#postBox').textContent);toast('Post copied')});if($('#copyPack'))$('#copyPack').addEventListener('click',async()=>{rebuild();await navigator.clipboard.writeText(JSON.stringify(pack(),null,2));toast('Pack copied')});if($('#pixabayKey'))$('#pixabayKey').addEventListener('input',save);if($('#pexelsKey'))$('#pexelsKey').addEventListener('input',save)}
load();bind();renderAll();