const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
const STORE='factpulse-v14';
let st={subject:'',fact:'',scene:'',details:'',length:30,mode:'broad',pixabay:'',pexels:'',clips:[],timeline:[]},lastBlob=null;
function clean(x){return String(x||'').trim().replace(/\s+/g,' ')}
function esc(x){return String(x||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;')}
function toast(x){let e=$('#toast');if(!e)return;e.textContent=x;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2400)}
function words(x){return clean(x).toLowerCase().split(/[^a-z0-9]+/).filter(w=>w.length>2&&!['the','and','for','with','that','this','from','into','about','after','before','when','what','why','how','was','were','are','his','her','their','who','has','had','have','did','does'].includes(w)).slice(0,18)}
function titleCase(x){return clean(x).split(' ').map(w=>w?w[0].toUpperCase()+w.slice(1).toLowerCase():'').join(' ')}
function title(){return (titleCase(st.subject||words(st.fact).slice(0,4).join(' ')||'Fact')+' Fact').toUpperCase().slice(0,70)}
function autoSceneText(text){let t=clean(text).toLowerCase();let map=[['court','courtroom judge lawyer courthouse trial hearing documents'],['trial','courtroom judge lawyer courthouse trial hearing documents'],['lawsuit','courtroom lawyer legal documents courthouse'],['crime','police lights courthouse handcuffs documents'],['president','speech podium flag crowd government'],['speech','speech podium microphone crowd'],['civil rights','civil rights march speech crowd protest'],['inventor','inventor lab electricity machine old footage'],['scientist','science lab microscope experiment'],['money','money cash bank finance coins wallet'],['space','space rocket planet astronaut galaxy'],['ocean','ocean waves underwater sea marine'],['animal','wild animals wildlife nature close up'],['history','archive footage crowd speech old city street'],['war','military soldiers battlefield archive footage'],['school','students classroom books studying'],['health','hospital doctor patient medical'],['food','food cooking kitchen close up'],['technology','computer phone circuit technology'],['weather','storm rain lightning clouds'],['sports','stadium athlete sports training'],['music','microphone concert crowd stage'],['car','cars road traffic city driving'],['earth','nature forest mountains landscape']];
for(let [k,v] of map)if(t.includes(k))return v;
return words(text).slice(0,7).join(' ')}
function searches(){let exact=clean(st.subject),scene=clean(st.scene)||autoSceneText(st.subject+' '+st.fact),keys=words(st.fact).slice(0,6).join(' ');return Array.from(new Set([exact,exact+' '+scene,scene,keys,scene+' b roll',scene+' stock video'].map(clean).filter(Boolean))).slice(0,7)}
function voice(){let f=clean(st.fact)||'This fact becomes easier to understand when the video shows the setting, movement, scale, and context.';return 'Did you know? '+f+' The key details are: '+(st.details||words(f).slice(0,4).join(', '))+'.'}
function save(){localStorage.setItem(STORE,JSON.stringify(st))}
function loadOld(){for(let k of ['factpulse-v14','factpulse-v13','factpulse-v12','factpulse-v11','factpulse-v10']){try{let x=JSON.parse(localStorage.getItem(k)||'{}');if(x.subject)st.subject=st.subject||x.subject;if(x.fact)st.fact=st.fact||x.fact;if(x.scene)st.scene=st.scene||x.scene;if(x.details)st.details=st.details||x.details;if(x.pixabayKey||x.key||x.pixabay)st.pixabay=x.pixabayKey||x.key||x.pixabay;if(x.pexelsKey||x.pexels)st.pexels=x.pexelsKey||x.pexels;if(x.current){st.subject=st.subject||x.current.subject||'';st.fact=st.fact||x.current.rawFact||x.current.fact||'';st.scene=st.scene||x.current.scene||x.current.query||'';st.details=st.details||x.current.numbers||''}if(x.clips&&!st.clips.length)st.clips=x.clips;if(x.timeline&&!st.timeline.length)st.timeline=x.timeline}catch(e){}}}
function load(){try{let x=JSON.parse(localStorage.getItem(STORE)||'{}');st={...st,...x}}catch(e){}loadOld();['subject','fact','scene','details','length','licenseMode','pixabayKey','pexelsKey'].forEach(id=>{let e=$('#'+id);if(!e)return;let k={licenseMode:'mode',pixabayKey:'pixabay',pexelsKey:'pexels'}[id]||id;e.value=st[k]||e.value||''});sync(false)}
function sync(write=true){['subject','fact','scene','details','length','licenseMode','pixabayKey','pexelsKey'].forEach(id=>{let e=$('#'+id);if(!e)return;let k={licenseMode:'mode',pixabayKey:'pixabay',pexelsKey:'pexels'}[id]||id;st[k]=e.value});st.length=Math.min(45,Math.max(25,Number(st.length)||30));if(write)save();renderPlan();renderClips();renderTimeline();renderPost()}
function renderPlan(){let e=$('#searchPlan');if(e)e.textContent=searches().map((x,i)=>(i+1)+'. '+x).join('\n')}
function renderPost(){let e=$('#postBox');if(!e)return;e.textContent=['TITLE: '+title(),'','VIDEO LENGTH: '+st.length+' seconds','','VOICEOVER:',voice(),'','DESCRIPTION:',title()+'\n\n'+st.fact+'\n\nKey details: '+st.details+'\n\n#shorts #facts #didyouknow','','CREDITS:',st.timeline.map(c=>c.credit+' via '+c.source+' | '+c.license+' | '+c.pageUrl).join('\n')].join('\n')}
async function wikiFill(){let subject=clean($('#subject')?$('#subject').value:st.subject);if(!subject){toast('Type a subject first.');return}toast('Getting fact and scene...');try{let searchUrl='https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch='+encodeURIComponent(subject)+'&format=json&origin=*';let sr=await fetch(searchUrl);let sj=await sr.json();let hit=sj.query&&sj.query.search&&sj.query.search[0];let titleText=hit?hit.title:subject;let sumUrl='https://en.wikipedia.org/api/rest_v1/page/summary/'+encodeURIComponent(titleText);let rr=await fetch(sumUrl);let data=rr.ok?await rr.json():{};let extract=clean(data.extract||hit&&hit.snippet&&hit.snippet.replace(/<[^>]+>/g,'')||subject);
let first=extract.split(/(?<=[.!?])\s+/).filter(Boolean).slice(0,2).join(' ');let desc=clean(data.description||'');let fact=first||subject+' is a topic people search for because the details, timeline, and context make it interesting.';let scene=autoSceneText(subject+' '+desc+' '+fact);let details=words(subject+' '+desc+' '+fact).slice(0,5).join(', ');
st.subject=titleText;st.fact=fact;st.scene=scene;st.details=details;if($('#subject'))$('#subject').value=st.subject;if($('#fact'))$('#fact').value=st.fact;if($('#scene'))$('#scene').value=st.scene;if($('#details'))$('#details').value=st.details;save();sync(false);toast('Auto filled from web info.')}catch(e){st.fact=subject+' is a topic where the setting, timeline, and context help explain the story.';st.scene=autoSceneText(subject);st.details=words(subject).slice(0,5).join(', ');if($('#fact'))$('#fact').value=st.fact;if($('#scene'))$('#scene').value=st.scene;if($('#details'))$('#details').value=st.details;sync(false);toast('Auto filled basic version.')}}
function isPub(l){l=clean(l).toLowerCase();return l.includes('public domain')||l.includes('cc0')||l.includes('pdm')}
function okLic(l){l=clean(l).toLowerCase();return isPub(l)||l.includes('cc by')||l.includes('pixabay')||l.includes('pexels')||l.includes('verify')||l===''||l.includes('unknown')}
function score(c){let text=(c.tags+' '+c.source+' '+c.pageUrl+' '+c.license).toLowerCase(),s=0;words(st.subject).forEach(w=>{if(text.includes(w))s+=12});words(st.scene+' '+st.fact).forEach(w=>{if(text.includes(w))s+=2});if(c.match==='exact')s+=35;if(c.source==='Wikimedia Commons')s+=3;if(c.source==='Internet Archive')s+=2;if(isPub(c.license))s+=4;return s}
async function fetchTimeout(url,opt={},ms=9000){let ctrl=new AbortController(),id=setTimeout(()=>ctrl.abort(),ms);try{return await fetch(url,{...opt,signal:ctrl.signal})}finally{clearTimeout(id)}}
function addResults(arr){let map=new Map(st.clips.map(c=>[c.id,c]));arr.forEach(c=>map.set(c.id,c));st.clips=[...map.values()].sort((a,b)=>score(b)-score(a)).slice(0,2000);save();renderClips();setStatus(st.clips.length+' clips loaded so far')}
function setStatus(x){let e=$('#clipCount');if(e)e.textContent=x}
async function commons(q,many,match){let out=[],off=0,limit=many?180:50;while(out.length<limit){let url='https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrnamespace=6&gsrlimit=50&gsroffset='+off+'&gsrsearch='+encodeURIComponent(q+' filetype:video')+'&prop=imageinfo&iiprop=url|mime|extmetadata&format=json&origin=*';let r=await fetchTimeout(url,{},8000);if(!r.ok)break;let j=await r.json(),pages=j.query&&j.query.pages?Object.values(j.query.pages):[];pages.forEach(p=>{let ii=p.imageinfo&&p.imageinfo[0];if(!ii||!String(ii.mime||'').startsWith('video/'))return;let m=ii.extmetadata||{},lic=(m.LicenseShortName&&m.LicenseShortName.value)||(m.UsageTerms&&m.UsageTerms.value)||'Unknown license';if(st.mode==='public'&&!isPub(lic))return;if(st.mode!=='public'&&!okLic(lic))return;out.push({id:'commons-'+p.pageid,source:'Wikimedia Commons',credit:(m.Artist&&m.Artist.value?m.Artist.value.replace(/<[^>]+>/g,''):'Wikimedia contributor'),pageUrl:'https://commons.wikimedia.org/wiki/'+encodeURIComponent(p.title.replaceAll(' ','_')),videoUrl:ii.url,previewUrl:ii.url,duration:0,tags:p.title+' '+q,license:lic,match})});if(!j.continue||!j.continue.gsroffset)break;off=j.continue.gsroffset}return out}
async function archive(q,many,match){let rows=many?220:60,url='https://archive.org/advancedsearch.php?q='+encodeURIComponent(q+' AND mediatype:movies')+'&fl[]=identifier&fl[]=title&fl[]=description&fl[]=licenseurl&fl[]=rights&rows='+rows+'&page=1&output=json';let r=await fetchTimeout(url,{},8000);if(!r.ok)return[];let j=await r.json(),docs=(j.response&&j.response.docs)||[],out=[];for(let d of docs.slice(0,many?50:18)){let lic=(d.licenseurl||d.rights||'verify source rights');if(st.mode==='public'&&!isPub(lic))continue;if(st.mode!=='public'&&!okLic(lic))continue;try{let m=await fetchTimeout('https://archive.org/metadata/'+encodeURIComponent(d.identifier),{},6500);if(!m.ok)continue;let meta=await m.json(),file=(meta.files||[]).find(f=>/\.mp4$/i.test(f.name)&&!String(f.name).toLowerCase().includes('thumb'));if(!file)continue;let src='https://archive.org/download/'+d.identifier+'/'+encodeURIComponent(file.name);out.push({id:'archive-'+d.identifier+'-'+file.name,source:'Internet Archive',credit:d.title||d.identifier,pageUrl:'https://archive.org/details/'+d.identifier,videoUrl:src,previewUrl:src,duration:Math.round(Number(file.length||0))||0,tags:(d.title||q)+' '+(d.description||''),license:lic,match})}catch(e){}}return out}
async function pixabay(q,many,match){if(!st.pixabay||st.mode==='public')return[];let all=[],pages=many?5:1;for(let p=1;p<=pages;p++){let r=await fetchTimeout('https://pixabay.com/api/videos/?key='+encodeURIComponent(st.pixabay)+'&q='+encodeURIComponent(q)+'&orientation=vertical&per_page='+(many?200:40)+'&page='+p+'&safesearch=true&order=popular',{},8000);if(!r.ok)break;let j=await r.json();(j.hits||[]).forEach(v=>{let f=v.videos&&((v.videos.medium)||(v.videos.small)||(v.videos.large)||(v.videos.tiny));if(f&&f.url)all.push({id:'pixabay-'+v.id,source:'Pixabay',credit:v.user||'Pixabay creator',pageUrl:v.pageURL,videoUrl:f.url,previewUrl:f.url,duration:v.duration||0,tags:v.tags||q,license:'Pixabay Content License',match})})}return all}
async function pexels(q,many,match){if(!st.pexels||st.mode==='public')return[];let all=[],pages=many?8:1;for(let p=1;p<=pages;p++){let r=await fetchTimeout('https://api.pexels.com/videos/search?query='+encodeURIComponent(q)+'&orientation=portrait&size=medium&per_page='+(many?80:40)+'&page='+p,{headers:{Authorization:st.pexels}},8000);if(!r.ok)break;let j=await r.json();(j.videos||[]).forEach(v=>{let f=(v.video_files||[]).filter(x=>x.link&&x.height>=x.width)[0]||(v.video_files||[])[0];if(f&&f.link)all.push({id:'pexels-'+v.id,source:'Pexels',credit:v.user&&v.user.name||'Pexels creator',pageUrl:v.url,videoUrl:f.link,previewUrl:f.link,duration:v.duration||0,tags:q,license:'Pexels License',match})})}return all}
async function searchClips(many){sync();st.clips=[];renderClips();let qs=searches();setStatus('Starting search...');for(let i=0;i<qs.length;i++){let q=qs[i],match=i<2?'exact':'related';let run=[['Wikimedia',commons],['Internet Archive',archive]];if(st.mode!=='public'){if(st.pixabay)run.unshift(['Pixabay',pixabay]);if(st.pexels)run.unshift(['Pexels',pexels])}for(let [name,fn] of run){try{setStatus('Searching '+name+': '+q);let res=await fn(q,many,match);if(res.length)addResults(res)}catch(e){}}}
setStatus(st.clips.length+' clips loaded');toast(st.clips.length?st.clips.length+' clips found':'No clips found. Add scene words or use Broad mode with a stock API key.')}
function addClip(i){let c=st.clips[i];if(!c)return;st.timeline.push(c);save();renderTimeline();renderPost();toast('Clip added')}
function modal(){if($('#clipModal'))return;let d=document.createElement('div');d.id='clipModal';d.innerHTML='<div class="modal-card"><button class="modal-close" id="closeModal" type="button">×</button><video id="modalVideo" controls playsinline></video><div class="box" id="modalInfo"></div><div class="two"><button class="btn primary" id="modalAdd" type="button">Add clip</button><a class="btn secondary" id="modalSource" target="_blank">Source</a></div></div>';document.body.appendChild(d);$('#closeModal').onclick=closePreview;d.onclick=e=>{if(e.target.id==='clipModal')closePreview()}}
function openPreview(i){let c=st.clips[i];if(!c)return;modal();$('#modalVideo').src=c.videoUrl;$('#modalVideo').play().catch(()=>{});$('#modalInfo').textContent=(c.match==='exact'?'Exact topic match':'Related B-roll')+'\n'+c.source+'\nLicense: '+c.license+'\nTopic: '+c.tags;$('#modalSource').href=c.pageUrl;$('#modalAdd').onclick=()=>{addClip(i);closePreview()};$('#clipModal').classList.add('show')}
function closePreview(){let v=$('#modalVideo'),m=$('#clipModal');if(v){v.pause();v.removeAttribute('src')}if(m)m.classList.remove('show')}
function renderClips(){let g=$('#clipGrid');if(!g)return;if($('#clipCount')&&!st.clips.length)$('#clipCount').textContent='0 clips loaded';g.innerHTML='';if(!st.clips.length){g.innerHTML='<div class="box">No clips loaded. Tap Find clips. The app searches exact subject first, then related B-roll.</div>';return}st.clips.forEach((c,i)=>{let label=c.match==='exact'?'EXACT TOPIC':'RELATED B-ROLL',el=document.createElement('article');el.className='clip';el.innerHTML='<div class="thumb"><video muted playsinline preload="metadata" src="'+c.previewUrl+'"></video></div><strong>'+label+' · '+esc(c.source)+'</strong><small>License: '+esc(c.license)+'</small><small>Topic: '+esc((c.tags||'').slice(0,100))+'</small><div class="row"><button type="button" data-p="'+i+'">Preview</button><button type="button" data-a="'+i+'">Add</button></div><a href="'+c.pageUrl+'" target="_blank">Source</a>';g.appendChild(el)});g.querySelectorAll('[data-p]').forEach(b=>b.onclick=()=>openPreview(Number(b.dataset.p)));g.querySelectorAll('[data-a]').forEach(b=>b.onclick=()=>addClip(Number(b.dataset.a)));g.querySelectorAll('.clip').forEach((card,i)=>card.onclick=e=>{if(!e.target.closest('button,a'))openPreview(i)})}
function renderTimeline(){let e=$('#timeline');if(!e)return;if($('#timelineCount'))$('#timelineCount').textContent=st.timeline.length+' clips selected. Final length: '+st.length+' seconds.';e.innerHTML=st.timeline.length?'':'<div class="box">No clips added yet.</div>';st.timeline.forEach((c,i)=>{let d=document.createElement('div');d.className='item';d.innerHTML='<div><strong>Clip '+(i+1)+' · '+esc(c.source)+'</strong><small>'+esc(c.license)+'</small><small>'+esc(c.pageUrl)+'</small></div><button type="button" data-rm="'+i+'">×</button>';e.appendChild(d)});e.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{st.timeline.splice(Number(b.dataset.rm),1);save();renderTimeline();renderPost()})}
function wrap(ctx,t,x,y,w,lh,max){let arr=t.split(' '),line='',lines=[];for(let a of arr){let test=line+a+' ';if(ctx.measureText(test).width>w&&line){lines.push(line.trim());line=a+' '}else line=test}lines.push(line.trim());lines.slice(0,max).forEach((l,i)=>ctx.fillText(l,x,y+i*lh))}
function draw(ctx,v,x,y,w,h){let vw=v.videoWidth||720,vh=v.videoHeight||1280,s=Math.max(w/vw,h/vh),sw=w/s,sh=h/s;ctx.drawImage(v,(vw-sw)/2,(vh-sh)/2,sw,sh,x,y,w,h)}
function loadVid(src){return new Promise((res,rej)=>{let v=document.createElement('video');v.crossOrigin='anonymous';v.muted=true;v.playsInline=true;v.src=src;v.onloadeddata=()=>res(v);v.onerror=rej})}
async function renderVideo(){sync();let can=$('#canvas'),ctx=can.getContext('2d'),dur=st.length;if(!can.captureStream||!window.MediaRecorder){toast('This browser cannot render video.');return}let vids=[];try{for(let c of st.timeline)vids.push(await loadVid(c.videoUrl))}catch(e){}let rec=new MediaRecorder(can.captureStream(24),{mimeType:MediaRecorder.isTypeSupported('video/webm;codecs=vp9')?'video/webm;codecs=vp9':'video/webm'}),chunks=[];rec.ondataavailable=e=>{if(e.data.size)chunks.push(e.data)};let done=new Promise(r=>rec.onstop=()=>r(new Blob(chunks,{type:'video/webm'})));rec.start();let start=performance.now();function frame(now){let t=Math.min((now-start)/1000,dur),top=430,bottom=110;ctx.fillStyle='#050505';ctx.fillRect(0,0,720,1280);if(vids.length){let i=Math.min(vids.length-1,Math.floor(t/(dur/vids.length))),v=vids[i];try{v.currentTime=(t%(Math.max(v.duration||4,1)));draw(ctx,v,0,top,720,1280-top-bottom)}catch(e){}}else{ctx.fillStyle='#1f6fb6';ctx.fillRect(0,top,720,1280-top-bottom)}ctx.fillStyle='#030303';ctx.fillRect(0,0,720,top);ctx.fillStyle='#18f038';ctx.font='900 56px -apple-system,Segoe UI,sans-serif';ctx.textAlign='center';ctx.fillText('DID YOU KNOW?',360,82);ctx.fillStyle='white';ctx.font='900 35px -apple-system,Segoe UI,sans-serif';wrap(ctx,st.fact,360,137,660,39,7);ctx.fillStyle='#050505';ctx.fillRect(0,1170,720,110);ctx.fillStyle='white';ctx.font='bold 29px -apple-system,Segoe UI,sans-serif';ctx.textAlign='left';ctx.fillText('@FactPulse',28,1215);ctx.font='bold 25px -apple-system,Segoe UI,sans-serif';ctx.fillText(title().slice(0,38),28,1256);if($('#progress'))$('#progress').style.width=(t/dur*100)+'%';if(t<dur)requestAnimationFrame(frame);else rec.stop()}requestAnimationFrame(frame);lastBlob=await done;let url=URL.createObjectURL(lastBlob);$('#videoOut').innerHTML='<video controls playsinline src="'+url+'"></video><a class="btn primary" href="'+url+'" download="factpulse-short.webm" style="margin-top:10px">Download styled video</a>';toast('Styled video rendered')}
function pack(){sync();return{title:title(),voiceover:voice(),description:st.fact,clips:st.timeline}}
function blobFile(name,content,type){let b=new Blob([content],{type}),u=URL.createObjectURL(b),a=document.createElement('a');a.href=u;a.download=name;a.click();URL.revokeObjectURL(u)}
function inject(){if($('#modalStyle'))return;let s=document.createElement('style');s.id='modalStyle';s.textContent='#clipModal{position:fixed;inset:0;z-index:200;background:rgba(0,0,0,.86);display:none;align-items:center;justify-content:center;padding:14px}#clipModal.show{display:flex}.modal-card{width:min(96vw,430px);max-height:92vh;overflow:auto;background:#111318;border:1px solid #2a2e38;border-radius:24px;padding:12px}.modal-card video{width:100%;max-height:58vh;background:#000;border-radius:18px}.modal-close{float:right;border:0;border-radius:999px;background:#18f038;color:#051007;font-weight:1000;width:40px;height:40px}.clip{cursor:pointer}.clip>a{display:block;margin-top:0}';document.head.appendChild(s)}
function bind(){inject();$$('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===(document.body.dataset.page||'create')));if($('#factForm'))$('#factForm').onsubmit=e=>{e.preventDefault();sync();location.href='clips-v14.html'};if($('#autoFill'))$('#autoFill').onclick=wikiFill;if($('#searchClips'))$('#searchClips').onclick=()=>searchClips(false);if($('#searchMany'))$('#searchMany').onclick=()=>searchClips(true);if($('#renderBtn'))$('#renderBtn').onclick=renderVideo;if($('#copyPost'))$('#copyPost').onclick=async()=>{sync();await navigator.clipboard.writeText($('#postBox').textContent);toast('Copied')};if($('#downloadPack'))$('#downloadPack').onclick=()=>blobFile('factpulse-edit-pack.json',JSON.stringify(pack(),null,2),'application/json');['subject','fact','scene','details','length','licenseMode','pixabayKey','pexelsKey'].forEach(id=>{let e=$('#'+id);if(e)e.addEventListener('input',sync);if(e&&id==='licenseMode')e.addEventListener('change',sync)})}
load();bind();renderPlan();renderClips();renderTimeline();renderPost();