const $=s=>document.querySelector(s),$$=s=>Array.from(document.querySelectorAll(s));
let current={},clips=[],timeline=[],lastBlob=null;
const STORE='factpulse-v11',OLD=['factpulse-v10','factpulse-v9','factpulse-v8'];
function clean(t){return String(t||'').trim().replace(/\s+/g,' ')}
function esc(t){return String(t||'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;').replaceAll("'",'&#039;')}
function toast(t){let e=$('#toast');if(!e)return;e.textContent=t;e.classList.add('show');setTimeout(()=>e.classList.remove('show'),2200)}
function words(t){return clean(t).toLowerCase().split(/[^a-z0-9]+/).filter(w=>w.length>2&&!['the','and','that','with','from','this','when','what','why','how','are','was','were','you','your','his','her','their','into','about'].includes(w)).slice(0,18)}
function titleCase(s){return clean(s).split(' ').map(w=>w?w[0].toUpperCase()+w.slice(1).toLowerCase():'').join(' ')}
function topic(t){let w=words(t).slice(0,4).join(' ');return titleCase(w||'This Fact')}
function save(){try{localStorage.setItem(STORE,JSON.stringify({current,clips,timeline,pixabayKey:$('#pixabayKey')?$('#pixabayKey').value:loadField('pixabayKey'),pexelsKey:$('#pexelsKey')?$('#pexelsKey').value:loadField('pexelsKey'),licenseMode:$('#licenseMode')?$('#licenseMode').value:(current.licenseMode||'broad')}))}catch(e){}}
function loadField(name){for(let k of [STORE,...OLD]){try{let s=localStorage.getItem(k);if(s){let st=JSON.parse(s);if(st[name])return st[name];if(name==='pixabayKey'&&st.key)return st.key}}catch(e){}}return ''}
function titleFrom(fact){return (topic(fact).toUpperCase()+' FACT').slice(0,70)}
function guessCategory(text){let t=clean(text).toLowerCase();let map=[['court','courtroom judge courthouse lawyer gavel trial hearing jury'],['trial','courtroom judge courthouse lawyer gavel trial hearing jury'],['lawsuit','courtroom documents lawyer courthouse'],['money','money cash bank business finance coins wallet'],['space','space rocket planet galaxy stars astronaut'],['ocean','ocean waves underwater sea marine'],['animal','wild animals nature close up wildlife'],['history','old city street archive crowd speech'],['war','soldiers battlefield military archive'],['school','students classroom studying books'],['health','doctor hospital medical patient'],['food','kitchen cooking food close up'],['science','laboratory microscope experiment science'],['crime','police lights courthouse handcuffs city night'],['technology','computer phone circuit technology'],['weather','storm clouds rain lightning weather'],['sports','stadium athlete training sports'],['music','microphone stage crowd concert'],['car','cars traffic road city driving'],['earth','nature forest mountain landscape earth']];
for(let [k,q] of map){if(t.includes(k))return q}
return words(text).slice(0,5).join(' ')}
function buildSearches(fact,manual){let exact=clean(manual)||clean(fact);let visual=guessCategory(fact+' '+manual);let keywords=words(fact).slice(0,6).join(' ');let list=[exact,visual,keywords,visual+' stock video',visual+' b roll'].map(clean).filter(Boolean);return Array.from(new Set(list)).slice(0,5)}
function buildCaption(fact){let f=clean(fact);let short=f.length>230?f.slice(0,227)+'...':f;return 'Did you know? '+short+' The key detail is what you can see in the clip: the setting, movement, scale, and context.'}
function rebuild(){let fact=$('#fact')?clean($('#fact').value):(current.fact||'A surprising fact becomes easier to understand when the video shows the setting, movement, scale, and context.');let manual=$('#query')?clean($('#query').value):(current.manualQuery||'');let len=$('#length')?Number($('#length').value):Number(current.length||30);len=Math.max(25,len||30);let details=$('#numbers')?clean($('#numbers').value):(current.numbers||words(fact).slice(0,4).join(', '));let searchList=buildSearches(fact,manual);let voice=buildCaption(fact);current={...current,fact,manualQuery:manual,query:searchList[0],searchList,numbers:details,length:len,title:titleFrom(fact),overlayPlain:'DID YOU KNOW?\n'+fact+'\nKey details: '+details,voiceover:voice,captions:voice.replace(/([.!?])\s+/g,'$1|').split('|').filter(Boolean),description:titleFrom(fact)+'\n\n'+fact+'\n\nKey details: '+details+'\n\n#shorts #facts #didyouknow #interestingfacts',licenseMode:$('#licenseMode')?$('#licenseMode').value:(current.licenseMode||'broad')};save();renderPost();renderTimeline();renderClips();renderSearchPlan()}
function load(){let raw=null;for(let k of [STORE,...OLD]){raw=localStorage.getItem(k);if(raw)break}if(raw){try{let st=JSON.parse(raw);current=st.current||{};clips=st.clips||[];timeline=st.timeline||[];if($('#pixabayKey'))$('#pixabayKey').value=st.pixabayKey||st.key||'';if($('#pexelsKey'))$('#pexelsKey').value=st.pexelsKey||'';if($('#licenseMode'))$('#licenseMode').value=st.licenseMode||current.licenseMode||'broad'}catch(e){}}
if(!current.fact)current.fact='A surprising fact becomes easier to understand when the video shows the setting, movement, scale, and context.';if($('#fact'))$('#fact').value=current.fact;if($('#query'))$('#query').value=current.manualQuery||current.query||'';if($('#numbers'))$('#numbers').value=current.numbers||'';if($('#length'))$('#length').value=String(Math.max(25,Number(current.length||30)));if($('#pixabayKey')&&!$('#pixabayKey').value)$('#pixabayKey').value=loadField('pixabayKey');if($('#pexelsKey')&&!$('#pexelsKey').value)$('#pexelsKey').value=loadField('pexelsKey');rebuild()}
function renderSearchPlan(){let e=$('#searchPlan');if(!e)return;e.textContent=(current.searchList||[]).map((x,i)=>(i+1)+'. '+x).join('\n')}
function isPublicLicense(x){x=clean(x).toLowerCase();return x.includes('public domain')||x.includes('cc0')||x.includes('pdm')}
function isPermissiveLicense(x){x=clean(x).toLowerCase();return isPublicLicense(x)||x.includes('cc by')||x.includes('creative commons attribution')||x.includes('cc-by')||x.includes('pixabay')||x.includes('pexels')||x===''}
function score(c,ts){let text=(c.tags+' '+c.source+' '+c.license+' '+c.pageUrl).toLowerCase();let s=0;ts.forEach(t=>{if(text.includes(t))s+=3});if(isPublicLicense(c.license))s+=4;if(c.source==='Wikimedia Commons')s+=3;if(c.source==='Internet Archive')s+=2;if(c.duration>=25)s+=1;return s}
async function searchCommons(q,many,mode){let limit=many?500:80,all=[],offset=0;while(all.length<limit){let url='https://commons.wikimedia.org/w/api.php?action=query&generator=search&gsrnamespace=6&gsrlimit=50&gsroffset='+offset+'&gsrsearch='+encodeURIComponent(q+' filetype:video')+'&prop=imageinfo&iiprop=url|mime|extmetadata&format=json&origin=*';let r=await fetch(url);if(!r.ok)break;let j=await r.json();let pages=j.query&&j.query.pages?Object.values(j.query.pages):[];pages.forEach(p=>{let ii=p.imageinfo&&p.imageinfo[0];if(!ii||!ii.url||!(ii.mime||'').startsWith('video/'))return;let meta=ii.extmetadata||{};let lic=(meta.LicenseShortName&&meta.LicenseShortName.value)||(meta.UsageTerms&&meta.UsageTerms.value)||'Unknown license';let ok=mode==='public'?isPublicLicense(lic):isPermissiveLicense(lic);if(!ok)return;let name=(p.title||'File').replace(/^File:/,'');all.push({id:'commons-'+p.pageid,source:'Wikimedia Commons',credit:(meta.Artist&&meta.Artist.value?meta.Artist.value.replace(/<[^>]+>/g,''):'Wikimedia contributor'),pageUrl:'https://commons.wikimedia.org/wiki/'+encodeURIComponent(p.title.replaceAll(' ','_')),videoUrl:ii.url,previewUrl:ii.url,duration:0,tags:name+' '+q,license:lic})});if(!j.continue||!j.continue.gsroffset)break;offset=j.continue.gsroffset}return all}
async function searchArchive(q,many,mode){let rows=many?1000:100;let url='https://archive.org/advancedsearch.php?q='+encodeURIComponent(q+' AND mediatype:movies')+'&fl[]=identifier&fl[]=title&fl[]=description&fl[]=licenseurl&fl[]=rights&rows='+rows+'&page=1&output=json';let r=await fetch(url);if(!r.ok)return[];let j=await r.json(),docs=(j.response&&j.response.docs)||[],out=[];let usable=docs.filter(d=>{let lic=(d.licenseurl||'')+' '+(d.rights||'');return mode==='public'?isPublicLicense(lic):isPermissiveLicense(lic)}).slice(0,many?120:45);for(let d of usable){try{let m=await fetch('https://archive.org/metadata/'+encodeURIComponent(d.identifier));if(!m.ok)continue;let meta=await m.json();let file=(meta.files||[]).find(f=>/\.mp4$/i.test(f.name)&&!String(f.name).toLowerCase().includes('thumb'));if(!file)continue;let lic=(d.licenseurl||d.rights||'verify source rights');if(mode==='public'&&!isPublicLicense(lic))continue;let src='https://archive.org/download/'+d.identifier+'/'+encodeURIComponent(file.name);out.push({id:'archive-'+d.identifier+'-'+file.name,source:'Internet Archive',credit:d.title||d.identifier,pageUrl:'https://archive.org/details/'+d.identifier,videoUrl:src,previewUrl:src,duration:Math.round(Number(file.length||0))||0,tags:(d.title||q)+' '+(d.description||''),license:lic})}catch(e){}}return out}
async function searchPixabay(q,key,many,mode){if(!key||mode==='public')return[];let pages=many?5:1,per=many?200:40,all=[];for(let p=1;p<=pages;p++){let url='https://pixabay.com/api/videos/?key='+encodeURIComponent(key)+'&q='+encodeURIComponent(q)+'&orientation=vertical&per_page='+per+'&page='+p+'&safesearch=true&order=popular';let r=await fetch(url);if(!r.ok)break;let j=await r.json();(j.hits||[]).forEach(v=>{let file=v.videos&&((v.videos.medium)||(v.videos.small)||(v.videos.large)||(v.videos.tiny));if(file&&file.url)all.push({id:'pixabay-'+v.id,source:'Pixabay',credit:v.user||'Pixabay creator',pageUrl:v.pageURL,videoUrl:file.url,previewUrl:file.url,duration:v.duration||0,tags:v.tags||q,license:'Pixabay Content License'})})}return all}
async function searchPexels(q,key,many,mode){if(!key||mode==='public')return[];let pages=many?13:1,per=many?80:40,all=[];for(let p=1;p<=pages;p++){let url='https://api.pexels.com/videos/search?query='+encodeURIComponent(q)+'&orientation=portrait&size=medium&per_page='+per+'&page='+p;let r=await fetch(url,{headers:{Authorization:key}});if(!r.ok)break;let j=await r.json();(j.videos||[]).forEach(v=>{let file=(v.video_files||[]).filter(f=>f.link&&f.height>=f.width).sort((a,b)=>Math.abs(a.height-1280)-Math.abs(b.height-1280))[0]||(v.video_files||[])[0];if(file&&file.link)all.push({id:'pexels-'+v.id,source:'Pexels',credit:v.user&&v.user.name||'Pexels creator',pageUrl:v.url,videoUrl:file.link,previewUrl:file.link,duration:v.duration||0,tags:q+' '+(v.user&&v.user.name||''),license:'Pexels License'})})}return all}
async function searchClips(many){rebuild();let mode=current.licenseMode||'broad';let pix=clean($('#pixabayKey')?$('#pixabayKey').value:''),pex=clean($('#pexelsKey')?$('#pexelsKey').value:'');clips=[];renderClips();let queries=current.searchList||[current.query];$('#clipCount').textContent='Searching multiple clip ideas...';try{let jobs=[];queries.forEach(q=>{jobs.push(searchCommons(q,many,mode),searchArchive(q,many,mode),searchPixabay(q,pix,many,mode),searchPexels(q,pex,many,mode))});let settled=await Promise.allSettled(jobs),results=[];settled.forEach(x=>{if(x.status==='fulfilled')results.push(...x.value)});let ts=words((queries.join(' ')+' '+current.fact));results.sort((a,b)=>score(b,ts)-score(a,ts));clips=Array.from(new Map(results.map(c=>[c.id,c])).values()).slice(0,many?2000:120);save();renderClips();$('#clipCount').textContent=clips.length+' clips loaded for this fact';if(!clips.length)toast('No clips found. Use broader scene words or Broad mode with Pixabay or Pexels.');else toast(clips.length+' clips found')}catch(e){$('#clipCount').textContent='Search failed';toast('Search failed. Try simpler scene words.')}} 
function addClip(i){let c=clips[i];if(!c)return;timeline.push(c);save();renderTimeline();renderPost();toast('Clip added')}
function modal(){if($('#clipModal'))return;let d=document.createElement('div');d.id='clipModal';d.innerHTML='<div class="modal-card"><button class="modal-close" id="closeModal" type="button">×</button><video id="modalVideo" controls playsinline></video><div class="box" id="modalInfo"></div><div class="two"><button class="btn primary" id="modalAdd" type="button">Add clip</button><a class="btn secondary" id="modalSource" target="_blank">Source</a></div></div>';document.body.appendChild(d);$('#closeModal').onclick=closePreview;d.onclick=e=>{if(e.target.id==='clipModal')closePreview()}}
function openPreview(i){let c=clips[i];if(!c)return;modal();let v=$('#modalVideo');v.src=c.videoUrl;v.play().catch(()=>{});$('#modalInfo').textContent=c.source+'\nLicense: '+(c.license||'verify source')+'\nTopic: '+(c.tags||current.query)+'\nLength: '+(c.duration?c.duration+' sec':'unknown');$('#modalSource').href=c.pageUrl;$('#modalAdd').onclick=()=>{addClip(i);closePreview()};$('#clipModal').classList.add('show')}
function closePreview(){let m=$('#clipModal'),v=$('#modalVideo');if(v){v.pause();v.removeAttribute('src')}if(m)m.classList.remove('show')}
function renderClips(){let g=$('#clipGrid');if(!g)return;if($('#clipCount'))$('#clipCount').textContent=clips.length?clips.length+' clips loaded':'0 clips loaded';g.innerHTML='';if(!clips.length){g.innerHTML='<div class="box">No clips loaded yet. Tap Find clips or Search thousands. For hard facts, use scene words like courtroom, city, crowd, hospital, school, storm, money, police, science lab, map, document, or old footage.</div>';return}clips.forEach((c,i)=>{let el=document.createElement('article');el.className='clip';el.dataset.i=i;el.innerHTML='<div class="thumb"><video muted playsinline preload="metadata" src="'+c.previewUrl+'"></video></div><strong>'+esc(c.source)+' clip '+(i+1)+'</strong><small>License: '+esc(c.license||'verify source')+'</small><small>Topic: '+esc((c.tags||'related').slice(0,100))+'</small><div class="row"><button type="button" data-preview="'+i+'">Preview</button><button type="button" data-add="'+i+'">Add</button></div><a href="'+c.pageUrl+'" target="_blank">Source</a>';g.appendChild(el)});g.querySelectorAll('[data-add]').forEach(b=>b.onclick=e=>{e.stopPropagation();addClip(Number(b.dataset.add))});g.querySelectorAll('[data-preview]').forEach(b=>b.onclick=e=>{e.stopPropagation();openPreview(Number(b.dataset.preview))});g.querySelectorAll('.clip').forEach(card=>{let v=card.querySelector('video');card.addEventListener('touchstart',()=>v&&v.play().catch(()=>{}),{passive:true});card.onclick=e=>{if(e.target.closest('a,button'))return;openPreview(Number(card.dataset.i))}})}
function renderTimeline(){let e=$('#timeline');if(!e)return;if($('#timelineCount'))$('#timelineCount').textContent=timeline.length+' clips selected. Final length: '+Math.max(25,Number(current.length||30))+' seconds.';e.innerHTML='';if(!timeline.length){e.innerHTML='<div class="box">No clips added yet.</div>';return}timeline.forEach((c,i)=>{let it=document.createElement('div');it.className='item';it.innerHTML='<div><strong>Clip '+(i+1)+' - '+esc(c.source)+'</strong><small>'+esc(c.license||'verify source')+'</small><small>'+esc(c.pageUrl)+'</small></div><button type="button" data-rm="'+i+'">×</button>';e.appendChild(it)});e.querySelectorAll('[data-rm]').forEach(b=>b.onclick=()=>{timeline.splice(Number(b.dataset.rm),1);save();renderTimeline();renderPost()})}
function renderPost(){let box=$('#postBox');if(!box)return;box.textContent=['TITLE: '+current.title,'','VIDEO LENGTH: '+current.length+' seconds','','VOICEOVER:',current.voiceover,'','CAPTIONS:',(current.captions||[]).join('\n\n'),'','DESCRIPTION:',current.description,'','CREDITS:',timeline.map(c=>c.credit+' via '+c.source+' | '+c.license+' | '+c.pageUrl).join('\n')].join('\n')}
function blobFile(name,content,type){let blob=new Blob([content],{type}),url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download=name;a.click();URL.revokeObjectURL(url)}
function pack(){rebuild();return{title:current.title,fact:current.fact,searchIdeas:current.searchList,lengthSeconds:current.length,voiceover:current.voiceover,captions:current.captions,description:current.description,selectedClips:timeline}}
function injectStyle(){if($('#modalStyle'))return;let s=document.createElement('style');s.id='modalStyle';s.textContent='#clipModal{position:fixed;inset:0;z-index:200;background:rgba(0,0,0,.86);display:none;align-items:center;justify-content:center;padding:14px}#clipModal.show{display:flex}.modal-card{width:min(96vw,430px);max-height:92vh;overflow:auto;background:#111318;border:1px solid #2a2e38;border-radius:24px;padding:12px}.modal-card video{width:100%;max-height:58vh;background:#000;border-radius:18px}.modal-close{float:right;border:0;border-radius:999px;background:#18f038;color:#051007;font-weight:1000;width:40px;height:40px}.clip{cursor:pointer}.clip>a{display:block;margin-top:0}';document.head.appendChild(s)}
function bind(){injectStyle();$$('[data-nav]').forEach(a=>a.classList.toggle('active',a.dataset.nav===(document.body.dataset.page||'create')));if($('#factForm'))$('#factForm').onsubmit=e=>{e.preventDefault();rebuild();location.href='clips-v11.html'};if($('#searchClips'))$('#searchClips').onclick=()=>searchClips(false);if($('#searchMany'))$('#searchMany').onclick=()=>searchClips(true);if($('#downloadPack'))$('#downloadPack').onclick=()=>blobFile('factpulse-edit-pack.json',JSON.stringify(pack(),null,2),'application/json');if($('#copyPost'))$('#copyPost').onclick=async()=>{rebuild();await navigator.clipboard.writeText($('#postBox').textContent);toast('Post copied')};['fact','query','numbers','length','licenseMode','pixabayKey','pexelsKey'].forEach(id=>{let e=$('#'+id);if(e)e.addEventListener('input',rebuild);if(e&&id==='licenseMode')e.addEventListener('change',rebuild)})}
load();bind();renderClips();renderTimeline();renderPost();renderSearchPlan();